/**
 * Add the checkout-abandonment-lockdown i18n keys to all 38 locale files.
 * customer.payment.* (6 keys) + email.orderStatus.* (2 keys).
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";

const LOCALES = readdirSync("src/messages").filter(f => f.endsWith(".json") && f !== "en.json").map(f => f.replace(".json", ""));

type Keys = {
  leaveConfirmTitle: string;
  leaveConfirmBody: string;
  leaveConfirmStay: string;
  leaveConfirmCancel: string;
  paymentInProgressWarning: string;
  cancelUnpaidFailed: string;
  cancelledPaymentIncompleteTitle: string;
  cancelledPaymentIncompleteBody: string;
};

const translations: Record<string, Keys> = {
  en: {
    leaveConfirmTitle: "Leave without paying?",
    leaveConfirmBody: "Going back now cancels this order — you won't be charged anything.",
    leaveConfirmStay: "Continue to payment",
    leaveConfirmCancel: "Cancel my order",
    paymentInProgressWarning: "Your payment is processing — please don't close this page.",
    cancelUnpaidFailed: "Couldn't cancel the order. Please try again.",
    cancelledPaymentIncompleteTitle: "Order cancelled — payment wasn't completed",
    cancelledPaymentIncompleteBody: "We didn't receive payment for this order in time, so it was cancelled automatically. If any hold was placed on your card or PayPal, it will be released — you have not been charged. Feel free to place a new order whenever you're ready.",
  },
  ar: {
    leaveConfirmTitle: "المغادرة بدون دفع؟",
    leaveConfirmBody: "الرجوع الآن يلغي هذا الطلب — لن يتم خصم أي مبلغ منك.",
    leaveConfirmStay: "متابعة الدفع",
    leaveConfirmCancel: "إلغاء طلبي",
    paymentInProgressWarning: "جارٍ معالجة الدفع — يرجى عدم إغلاق هذه الصفحة.",
    cancelUnpaidFailed: "تعذر إلغاء الطلب. يرجى المحاولة مرة أخرى.",
    cancelledPaymentIncompleteTitle: "تم إلغاء الطلب — لم يكتمل الدفع",
    cancelledPaymentIncompleteBody: "لم نستلم الدفع لهذا الطلب في الوقت المحدد، لذا تم إلغاؤه تلقائيًا. إذا تم حجز أي مبلغ على بطاقتك أو باي بال، فسيتم تحريره — لم يتم خصم أي مبلغ منك. لا تتردد في تقديم طلب جديد متى شئت.",
  },
  bg: {
    leaveConfirmTitle: "Излизане без плащане?",
    leaveConfirmBody: "Връщането сега отменя тази поръчка — няма да бъдете таксувани.",
    leaveConfirmStay: "Продължи към плащане",
    leaveConfirmCancel: "Отмени поръчката ми",
    paymentInProgressWarning: "Плащането се обработва — моля, не затваряйте тази страница.",
    cancelUnpaidFailed: "Поръчката не можа да бъде отменена. Моля, опитайте отново.",
    cancelledPaymentIncompleteTitle: "Поръчката е отменена — плащането не бе завършено",
    cancelledPaymentIncompleteBody: "Не получихме плащане за тази поръчка навреме, затова тя бе автоматично отменена. Ако е имало задържане на картата или PayPal, то ще бъде освободено — не сте таксувани. Можете да направите нова поръчка, когато сте готови.",
  },
  ca: {
    leaveConfirmTitle: "Sortir sense pagar?",
    leaveConfirmBody: "Si tornes enrere ara, es cancel·la aquesta comanda — no se't cobrarà res.",
    leaveConfirmStay: "Continua amb el pagament",
    leaveConfirmCancel: "Cancel·la la meva comanda",
    paymentInProgressWarning: "El pagament s'està processant — no tanquis aquesta pàgina.",
    cancelUnpaidFailed: "No s'ha pogut cancel·lar la comanda. Torna-ho a provar.",
    cancelledPaymentIncompleteTitle: "Comanda cancel·lada — el pagament no s'ha completat",
    cancelledPaymentIncompleteBody: "No hem rebut el pagament d'aquesta comanda a temps, així que s'ha cancel·lat automàticament. Si hi havia una retenció a la teva targeta o PayPal, s'alliberarà — no se t'ha cobrat res. Pots fer una nova comanda quan vulguis.",
  },
  cs: {
    leaveConfirmTitle: "Odejít bez zaplacení?",
    leaveConfirmBody: "Návrat nyní zruší tuto objednávku — nebude vám nic účtováno.",
    leaveConfirmStay: "Pokračovat k platbě",
    leaveConfirmCancel: "Zrušit mou objednávku",
    paymentInProgressWarning: "Platba se zpracovává — nezavírejte prosím tuto stránku.",
    cancelUnpaidFailed: "Objednávku se nepodařilo zrušit. Zkuste to prosím znovu.",
    cancelledPaymentIncompleteTitle: "Objednávka zrušena — platba nebyla dokončena",
    cancelledPaymentIncompleteBody: "Platbu za tuto objednávku jsme včas neobdrželi, proto byla automaticky zrušena. Pokud byla na vaší kartě nebo PayPal provedena rezervace částky, bude uvolněna — nebylo vám nic účtováno. Novou objednávku můžete zadat kdykoli budete chtít.",
  },
  da: {
    leaveConfirmTitle: "Forlad uden at betale?",
    leaveConfirmBody: "Hvis du går tilbage nu, annulleres denne ordre — du bliver ikke opkrævet noget.",
    leaveConfirmStay: "Fortsæt til betaling",
    leaveConfirmCancel: "Annuller min ordre",
    paymentInProgressWarning: "Din betaling behandles — luk ikke denne side.",
    cancelUnpaidFailed: "Kunne ikke annullere ordren. Prøv venligst igen.",
    cancelledPaymentIncompleteTitle: "Ordre annulleret — betaling ikke gennemført",
    cancelledPaymentIncompleteBody: "Vi modtog ikke betaling for denne ordre i tide, så den blev automatisk annulleret. Hvis der var en reservation på dit kort eller PayPal, frigives den — du er ikke blevet opkrævet. Du er velkommen til at afgive en ny ordre, når du er klar.",
  },
  de: {
    leaveConfirmTitle: "Ohne Bezahlung verlassen?",
    leaveConfirmBody: "Wenn du jetzt zurückgehst, wird diese Bestellung storniert — dir wird nichts berechnet.",
    leaveConfirmStay: "Zur Zahlung fortfahren",
    leaveConfirmCancel: "Bestellung stornieren",
    paymentInProgressWarning: "Deine Zahlung wird verarbeitet — bitte schließe diese Seite nicht.",
    cancelUnpaidFailed: "Bestellung konnte nicht storniert werden. Bitte versuche es erneut.",
    cancelledPaymentIncompleteTitle: "Bestellung storniert — Zahlung nicht abgeschlossen",
    cancelledPaymentIncompleteBody: "Wir haben die Zahlung für diese Bestellung nicht rechtzeitig erhalten, daher wurde sie automatisch storniert. Falls eine Reservierung auf deiner Karte oder PayPal vorgenommen wurde, wird sie freigegeben — dir wurde nichts berechnet. Du kannst jederzeit eine neue Bestellung aufgeben.",
  },
  el: {
    leaveConfirmTitle: "Έξοδος χωρίς πληρωμή;",
    leaveConfirmBody: "Αν επιστρέψετε τώρα, η παραγγελία θα ακυρωθεί — δεν θα χρεωθείτε τίποτα.",
    leaveConfirmStay: "Συνέχεια στην πληρωμή",
    leaveConfirmCancel: "Ακύρωση της παραγγελίας μου",
    paymentInProgressWarning: "Η πληρωμή σας επεξεργάζεται — μην κλείσετε αυτή τη σελίδα.",
    cancelUnpaidFailed: "Δεν ήταν δυνατή η ακύρωση της παραγγελίας. Δοκιμάστε ξανά.",
    cancelledPaymentIncompleteTitle: "Η παραγγελία ακυρώθηκε — η πληρωμή δεν ολοκληρώθηκε",
    cancelledPaymentIncompleteBody: "Δεν λάβαμε πληρωμή για αυτή την παραγγελία εγκαίρως, οπότε ακυρώθηκε αυτόματα. Αν είχε γίνει κράτηση ποσού στην κάρτα σας ή στο PayPal, θα απελευθερωθεί — δεν έχετε χρεωθεί. Μπορείτε να κάνετε νέα παραγγελία όποτε είστε έτοιμοι.",
  },
  es: {
    leaveConfirmTitle: "¿Salir sin pagar?",
    leaveConfirmBody: "Si vuelves atrás ahora, se cancelará este pedido — no se te cobrará nada.",
    leaveConfirmStay: "Continuar con el pago",
    leaveConfirmCancel: "Cancelar mi pedido",
    paymentInProgressWarning: "Tu pago se está procesando — por favor no cierres esta página.",
    cancelUnpaidFailed: "No se pudo cancelar el pedido. Inténtalo de nuevo.",
    cancelledPaymentIncompleteTitle: "Pedido cancelado — el pago no se completó",
    cancelledPaymentIncompleteBody: "No recibimos el pago de este pedido a tiempo, así que se canceló automáticamente. Si se retuvo algún importe en tu tarjeta o PayPal, se liberará — no se te ha cobrado nada. Puedes hacer un nuevo pedido cuando quieras.",
  },
  et: {
    leaveConfirmTitle: "Lahkuda ilma maksmata?",
    leaveConfirmBody: "Kui lähed nüüd tagasi, tühistatakse see tellimus — sinult ei võeta midagi.",
    leaveConfirmStay: "Jätka maksmist",
    leaveConfirmCancel: "Tühista mu tellimus",
    paymentInProgressWarning: "Sinu makset töödeldakse — palun ära sulge seda lehte.",
    cancelUnpaidFailed: "Tellimust ei õnnestunud tühistada. Palun proovi uuesti.",
    cancelledPaymentIncompleteTitle: "Tellimus tühistatud — makse ei õnnestunud",
    cancelledPaymentIncompleteBody: "Me ei saanud selle tellimuse eest õigeaegselt makset, seega tühistati see automaatselt. Kui teie kaardil või PayPalis oli reserveering, see vabastatakse — teilt ei ole midagi maha võetud. Võite igal ajal uue tellimuse esitada.",
  },
  fi: {
    leaveConfirmTitle: "Poistu maksamatta?",
    leaveConfirmBody: "Jos palaat nyt takaisin, tilaus perutaan — sinulta ei veloiteta mitään.",
    leaveConfirmStay: "Jatka maksamiseen",
    leaveConfirmCancel: "Peru tilaukseni",
    paymentInProgressWarning: "Maksuasi käsitellään — älä sulje tätä sivua.",
    cancelUnpaidFailed: "Tilauksen peruuttaminen epäonnistui. Yritä uudelleen.",
    cancelledPaymentIncompleteTitle: "Tilaus peruttu — maksua ei suoritettu loppuun",
    cancelledPaymentIncompleteBody: "Emme saaneet maksua tästä tilauksesta ajoissa, joten se peruttiin automaattisesti. Jos kortillesi tai PayPaliisi tehtiin varaus, se vapautetaan — sinulta ei ole veloitettu mitään. Voit tehdä uuden tilauksen milloin tahansa.",
  },
  fr: {
    leaveConfirmTitle: "Quitter sans payer ?",
    leaveConfirmBody: "Si vous revenez en arrière maintenant, cette commande sera annulée — vous ne serez pas débité.",
    leaveConfirmStay: "Continuer le paiement",
    leaveConfirmCancel: "Annuler ma commande",
    paymentInProgressWarning: "Votre paiement est en cours de traitement — merci de ne pas fermer cette page.",
    cancelUnpaidFailed: "Impossible d'annuler la commande. Veuillez réessayer.",
    cancelledPaymentIncompleteTitle: "Commande annulée — paiement non finalisé",
    cancelledPaymentIncompleteBody: "Nous n'avons pas reçu le paiement de cette commande à temps, elle a donc été annulée automatiquement. Si une réservation avait été faite sur votre carte ou PayPal, elle sera libérée — vous n'avez pas été débité. N'hésitez pas à passer une nouvelle commande quand vous le souhaitez.",
  },
  he: {
    leaveConfirmTitle: "לצאת בלי לשלם?",
    leaveConfirmBody: "אם תחזור עכשיו, ההזמנה תבוטל — לא תחויב בכלום.",
    leaveConfirmStay: "המשך לתשלום",
    leaveConfirmCancel: "בטל את ההזמנה שלי",
    paymentInProgressWarning: "התשלום שלך בעיבוד — נא לא לסגור את הדף הזה.",
    cancelUnpaidFailed: "לא ניתן היה לבטל את ההזמנה. נסה שוב.",
    cancelledPaymentIncompleteTitle: "ההזמנה בוטלה — התשלום לא הושלם",
    cancelledPaymentIncompleteBody: "לא קיבלנו תשלום עבור הזמנה זו בזמן, ולכן היא בוטלה אוטומטית. אם הייתה החזקת סכום בכרטיס שלך או ב-PayPal, היא תשוחרר — לא חויבת בכלום. מוזמן להזמין שוב מתי שתרצה.",
  },
  hi: {
    leaveConfirmTitle: "बिना भुगतान किए बाहर जाएं?",
    leaveConfirmBody: "अभी वापस जाने से यह ऑर्डर रद्द हो जाएगा — आपसे कोई शुल्क नहीं लिया जाएगा।",
    leaveConfirmStay: "भुगतान जारी रखें",
    leaveConfirmCancel: "मेरा ऑर्डर रद्द करें",
    paymentInProgressWarning: "आपका भुगतान प्रोसेस हो रहा है — कृपया इस पेज को बंद न करें।",
    cancelUnpaidFailed: "ऑर्डर रद्द नहीं किया जा सका। कृपया पुनः प्रयास करें।",
    cancelledPaymentIncompleteTitle: "ऑर्डर रद्द — भुगतान पूरा नहीं हुआ",
    cancelledPaymentIncompleteBody: "हमें इस ऑर्डर का भुगतान समय पर नहीं मिला, इसलिए इसे स्वचालित रूप से रद्द कर दिया गया। यदि आपके कार्ड या PayPal पर कोई राशि होल्ड की गई थी, तो वह जारी कर दी जाएगी — आपसे कोई शुल्क नहीं लिया गया है। जब चाहें एक नया ऑर्डर दे सकते हैं।",
  },
  hr: {
    leaveConfirmTitle: "Izaći bez plaćanja?",
    leaveConfirmBody: "Ako se sada vratite, ova narudžba će biti otkazana — neće vam biti ništa naplaćeno.",
    leaveConfirmStay: "Nastavi s plaćanjem",
    leaveConfirmCancel: "Otkaži moju narudžbu",
    paymentInProgressWarning: "Vaše plaćanje se obrađuje — nemojte zatvarati ovu stranicu.",
    cancelUnpaidFailed: "Narudžbu nije bilo moguće otkazati. Pokušajte ponovno.",
    cancelledPaymentIncompleteTitle: "Narudžba otkazana — plaćanje nije dovršeno",
    cancelledPaymentIncompleteBody: "Nismo na vrijeme primili uplatu za ovu narudžbu, pa je automatski otkazana. Ako je na vašoj kartici ili PayPalu bila rezervacija iznosa, ona će biti oslobođena — ništa vam nije naplaćeno. Slobodno naručite ponovno kad budete spremni.",
  },
  hu: {
    leaveConfirmTitle: "Fizetés nélkül távozol?",
    leaveConfirmBody: "Ha most visszalépsz, ez a rendelés törlődik — nem terhelünk semmit.",
    leaveConfirmStay: "Fizetés folytatása",
    leaveConfirmCancel: "Rendelés törlése",
    paymentInProgressWarning: "A fizetésed feldolgozás alatt van — kérjük, ne zárd be ezt az oldalt.",
    cancelUnpaidFailed: "A rendelést nem sikerült törölni. Kérjük, próbáld újra.",
    cancelledPaymentIncompleteTitle: "Rendelés törölve — a fizetés nem fejeződött be",
    cancelledPaymentIncompleteBody: "Nem érkezett meg időben a fizetés ehhez a rendeléshez, ezért automatikusan törlésre került. Ha a kártyádon vagy PayPal fiókodon zárolás történt, az feloldásra kerül — nem terheltünk semmit. Bármikor leadhatsz új rendelést.",
  },
  id: {
    leaveConfirmTitle: "Keluar tanpa membayar?",
    leaveConfirmBody: "Kembali sekarang akan membatalkan pesanan ini — Anda tidak akan dikenakan biaya apa pun.",
    leaveConfirmStay: "Lanjutkan pembayaran",
    leaveConfirmCancel: "Batalkan pesanan saya",
    paymentInProgressWarning: "Pembayaran Anda sedang diproses — mohon jangan tutup halaman ini.",
    cancelUnpaidFailed: "Pesanan tidak dapat dibatalkan. Silakan coba lagi.",
    cancelledPaymentIncompleteTitle: "Pesanan dibatalkan — pembayaran tidak selesai",
    cancelledPaymentIncompleteBody: "Kami tidak menerima pembayaran untuk pesanan ini tepat waktu, sehingga dibatalkan secara otomatis. Jika ada penahanan dana pada kartu atau PayPal Anda, itu akan dilepaskan — Anda tidak dikenakan biaya. Silakan buat pesanan baru kapan pun Anda siap.",
  },
  it: {
    leaveConfirmTitle: "Uscire senza pagare?",
    leaveConfirmBody: "Se torni indietro ora, questo ordine verrà annullato — non ti verrà addebitato nulla.",
    leaveConfirmStay: "Continua al pagamento",
    leaveConfirmCancel: "Annulla il mio ordine",
    paymentInProgressWarning: "Il pagamento è in corso di elaborazione — non chiudere questa pagina.",
    cancelUnpaidFailed: "Impossibile annullare l'ordine. Riprova.",
    cancelledPaymentIncompleteTitle: "Ordine annullato — pagamento non completato",
    cancelledPaymentIncompleteBody: "Non abbiamo ricevuto il pagamento per questo ordine in tempo, quindi è stato annullato automaticamente. Se era stata effettuata una prenotazione sulla tua carta o PayPal, verrà rilasciata — non ti è stato addebitato nulla. Puoi effettuare un nuovo ordine quando vuoi.",
  },
  ja: {
    leaveConfirmTitle: "支払わずに離れますか？",
    leaveConfirmBody: "今戻ると、このご注文はキャンセルされます — 料金は一切発生しません。",
    leaveConfirmStay: "支払いを続ける",
    leaveConfirmCancel: "注文をキャンセルする",
    paymentInProgressWarning: "お支払いを処理中です — このページを閉じないでください。",
    cancelUnpaidFailed: "注文をキャンセルできませんでした。もう一度お試しください。",
    cancelledPaymentIncompleteTitle: "注文がキャンセルされました — お支払いが完了しませんでした",
    cancelledPaymentIncompleteBody: "このご注文のお支払いを時間内に受け取れなかったため、自動的にキャンセルされました。カードまたはPayPalに保留があった場合は解除されます — 料金は発生していません。ご準備ができましたら、いつでも新しいご注文をどうぞ。",
  },
  ko: {
    leaveConfirmTitle: "결제 없이 나가시겠습니까?",
    leaveConfirmBody: "지금 뒤로 가면 이 주문이 취소됩니다 — 요금은 청구되지 않습니다.",
    leaveConfirmStay: "결제 계속하기",
    leaveConfirmCancel: "주문 취소하기",
    paymentInProgressWarning: "결제가 처리 중입니다 — 이 페이지를 닫지 마세요.",
    cancelUnpaidFailed: "주문을 취소할 수 없습니다. 다시 시도해 주세요.",
    cancelledPaymentIncompleteTitle: "주문 취소됨 — 결제가 완료되지 않았습니다",
    cancelledPaymentIncompleteBody: "이 주문에 대한 결제를 제시간에 받지 못해 자동으로 취소되었습니다. 카드나 PayPal에 보류된 금액이 있다면 해제됩니다 — 요금은 청구되지 않았습니다. 준비되시면 언제든지 새 주문을 해 주세요.",
  },
  lt: {
    leaveConfirmTitle: "Išeiti nesumokėjus?",
    leaveConfirmBody: "Jei dabar grįšite, šis užsakymas bus atšauktas — jums nebus nieko nuskaičiuota.",
    leaveConfirmStay: "Tęsti mokėjimą",
    leaveConfirmCancel: "Atšaukti mano užsakymą",
    paymentInProgressWarning: "Jūsų mokėjimas apdorojamas — nedarykite šio puslapio uždarymo.",
    cancelUnpaidFailed: "Nepavyko atšaukti užsakymo. Bandykite dar kartą.",
    cancelledPaymentIncompleteTitle: "Užsakymas atšauktas — mokėjimas nebaigtas",
    cancelledPaymentIncompleteBody: "Negavome mokėjimo už šį užsakymą laiku, todėl jis buvo automatiškai atšauktas. Jei jūsų kortelėje ar PayPal buvo rezervuota suma, ji bus atlaisvinta — jums nieko nenuskaičiuota. Galite pateikti naują užsakymą, kai tik būsite pasiruošę.",
  },
  lv: {
    leaveConfirmTitle: "Iziet nesamaksājot?",
    leaveConfirmBody: "Ja tagad atgriezīsieties, šis pasūtījums tiks atcelts — no jums netiks iekasēta nauda.",
    leaveConfirmStay: "Turpināt apmaksu",
    leaveConfirmCancel: "Atcelt manu pasūtījumu",
    paymentInProgressWarning: "Jūsu maksājums tiek apstrādāts — lūdzu, neaizveriet šo lapu.",
    cancelUnpaidFailed: "Neizdevās atcelt pasūtījumu. Lūdzu, mēģiniet vēlreiz.",
    cancelledPaymentIncompleteTitle: "Pasūtījums atcelts — maksājums netika pabeigts",
    cancelledPaymentIncompleteBody: "Mēs savlaicīgi nesaņēmām maksājumu par šo pasūtījumu, tāpēc tas tika automātiski atcelts. Ja jūsu kartē vai PayPal bija veikta rezervācija, tā tiks atbrīvota — no jums netika iekasēta nauda. Varat veikt jaunu pasūtījumu, tiklīdz būsiet gatavs.",
  },
  nb: {
    leaveConfirmTitle: "Forlate uten å betale?",
    leaveConfirmBody: "Hvis du går tilbake nå, blir denne bestillingen kansellert — du blir ikke belastet noe.",
    leaveConfirmStay: "Fortsett til betaling",
    leaveConfirmCancel: "Kanseller bestillingen min",
    paymentInProgressWarning: "Betalingen din behandles — ikke lukk denne siden.",
    cancelUnpaidFailed: "Kunne ikke kansellere bestillingen. Prøv igjen.",
    cancelledPaymentIncompleteTitle: "Bestilling kansellert — betaling ikke fullført",
    cancelledPaymentIncompleteBody: "Vi mottok ikke betaling for denne bestillingen i tide, så den ble automatisk kansellert. Hvis det var en reservasjon på kortet ditt eller PayPal, blir den frigjort — du er ikke belastet noe. Du kan legge inn en ny bestilling når du er klar.",
  },
  nl: {
    leaveConfirmTitle: "Vertrekken zonder te betalen?",
    leaveConfirmBody: "Als je nu teruggaat, wordt deze bestelling geannuleerd — er wordt niets in rekening gebracht.",
    leaveConfirmStay: "Doorgaan met betalen",
    leaveConfirmCancel: "Bestelling annuleren",
    paymentInProgressWarning: "Je betaling wordt verwerkt — sluit deze pagina niet.",
    cancelUnpaidFailed: "Bestelling kon niet worden geannuleerd. Probeer het opnieuw.",
    cancelledPaymentIncompleteTitle: "Bestelling geannuleerd — betaling niet voltooid",
    cancelledPaymentIncompleteBody: "We hebben de betaling voor deze bestelling niet op tijd ontvangen, dus is deze automatisch geannuleerd. Als er een reservering was op je kaart of PayPal, wordt deze vrijgegeven — er is niets in rekening gebracht. Plaats gerust een nieuwe bestelling wanneer je klaar bent.",
  },
  pl: {
    leaveConfirmTitle: "Wyjść bez płacenia?",
    leaveConfirmBody: "Powrót teraz anuluje to zamówienie — nie zostaniesz obciążony żadną kwotą.",
    leaveConfirmStay: "Kontynuuj płatność",
    leaveConfirmCancel: "Anuluj moje zamówienie",
    paymentInProgressWarning: "Twoja płatność jest przetwarzana — nie zamykaj tej strony.",
    cancelUnpaidFailed: "Nie udało się anulować zamówienia. Spróbuj ponownie.",
    cancelledPaymentIncompleteTitle: "Zamówienie anulowane — płatność nie została ukończona",
    cancelledPaymentIncompleteBody: "Nie otrzymaliśmy na czas płatności za to zamówienie, więc zostało ono automatycznie anulowane. Jeśli na Twojej karcie lub PayPal dokonano blokady środków, zostanie ona zwolniona — nie zostałeś obciążony żadną kwotą. Możesz złożyć nowe zamówienie, kiedy tylko zechcesz.",
  },
  "pt-BR": {
    leaveConfirmTitle: "Sair sem pagar?",
    leaveConfirmBody: "Se você voltar agora, este pedido será cancelado — você não será cobrado.",
    leaveConfirmStay: "Continuar para o pagamento",
    leaveConfirmCancel: "Cancelar meu pedido",
    paymentInProgressWarning: "Seu pagamento está sendo processado — não feche esta página.",
    cancelUnpaidFailed: "Não foi possível cancelar o pedido. Tente novamente.",
    cancelledPaymentIncompleteTitle: "Pedido cancelado — pagamento não concluído",
    cancelledPaymentIncompleteBody: "Não recebemos o pagamento deste pedido a tempo, então ele foi cancelado automaticamente. Se houve alguma retenção no seu cartão ou PayPal, ela será liberada — você não foi cobrado. Sinta-se à vontade para fazer um novo pedido quando estiver pronto.",
  },
  pt: {
    leaveConfirmTitle: "Sair sem pagar?",
    leaveConfirmBody: "Se voltar agora, esta encomenda será cancelada — não lhe será cobrado nada.",
    leaveConfirmStay: "Continuar para o pagamento",
    leaveConfirmCancel: "Cancelar a minha encomenda",
    paymentInProgressWarning: "O seu pagamento está a ser processado — não feche esta página.",
    cancelUnpaidFailed: "Não foi possível cancelar a encomenda. Tente novamente.",
    cancelledPaymentIncompleteTitle: "Encomenda cancelada — pagamento não concluído",
    cancelledPaymentIncompleteBody: "Não recebemos o pagamento desta encomenda a tempo, pelo que foi cancelada automaticamente. Se houve alguma retenção no seu cartão ou PayPal, esta será libertada — não lhe foi cobrado nada. Sinta-se à vontade para fazer uma nova encomenda quando estiver pronto.",
  },
  ro: {
    leaveConfirmTitle: "Pleci fără să plătești?",
    leaveConfirmBody: "Dacă revii acum, această comandă va fi anulată — nu vei fi taxat cu nimic.",
    leaveConfirmStay: "Continuă plata",
    leaveConfirmCancel: "Anulează comanda mea",
    paymentInProgressWarning: "Plata ta este în curs de procesare — te rugăm să nu închizi această pagină.",
    cancelUnpaidFailed: "Comanda nu a putut fi anulată. Te rugăm să încerci din nou.",
    cancelledPaymentIncompleteTitle: "Comandă anulată — plata nu a fost finalizată",
    cancelledPaymentIncompleteBody: "Nu am primit plata pentru această comandă la timp, așa că a fost anulată automat. Dacă a existat o rezervare pe cardul tău sau PayPal, aceasta va fi eliberată — nu ai fost taxat cu nimic. Poți plasa o comandă nouă oricând ești pregătit.",
  },
  ru: {
    leaveConfirmTitle: "Выйти без оплаты?",
    leaveConfirmBody: "Если вы вернётесь сейчас, этот заказ будет отменён — с вас ничего не спишут.",
    leaveConfirmStay: "Продолжить оплату",
    leaveConfirmCancel: "Отменить мой заказ",
    paymentInProgressWarning: "Ваш платёж обрабатывается — пожалуйста, не закрывайте эту страницу.",
    cancelUnpaidFailed: "Не удалось отменить заказ. Пожалуйста, попробуйте снова.",
    cancelledPaymentIncompleteTitle: "Заказ отменён — оплата не завершена",
    cancelledPaymentIncompleteBody: "Мы не получили оплату за этот заказ вовремя, поэтому он был автоматически отменён. Если на вашей карте или PayPal была произведена блокировка средств, она будет снята — с вас ничего не списано. Вы можете оформить новый заказ, когда будете готовы.",
  },
  sk: {
    leaveConfirmTitle: "Odísť bez zaplatenia?",
    leaveConfirmBody: "Ak sa teraz vrátite, táto objednávka bude zrušená — nebude vám nič účtované.",
    leaveConfirmStay: "Pokračovať k platbe",
    leaveConfirmCancel: "Zrušiť moju objednávku",
    paymentInProgressWarning: "Vaša platba sa spracováva — túto stránku prosím nezatvárajte.",
    cancelUnpaidFailed: "Objednávku sa nepodarilo zrušiť. Skúste to prosím znova.",
    cancelledPaymentIncompleteTitle: "Objednávka zrušená — platba nebola dokončená",
    cancelledPaymentIncompleteBody: "Platbu za túto objednávku sme včas nedostali, preto bola automaticky zrušená. Ak bola na vašej karte alebo PayPal vykonaná rezervácia sumy, bude uvoľnená — nič vám nebolo účtované. Novú objednávku môžete zadať kedykoľvek budete pripravení.",
  },
  sl: {
    leaveConfirmTitle: "Zapustiti brez plačila?",
    leaveConfirmBody: "Če se zdaj vrnete, bo to naročilo preklicano — ne bo vam zaračunano nič.",
    leaveConfirmStay: "Nadaljuj s plačilom",
    leaveConfirmCancel: "Prekliči moje naročilo",
    paymentInProgressWarning: "Vaše plačilo se obdeluje — te strani ne zapirajte.",
    cancelUnpaidFailed: "Naročila ni bilo mogoče preklicati. Poskusite znova.",
    cancelledPaymentIncompleteTitle: "Naročilo preklicano — plačilo ni bilo dokončano",
    cancelledPaymentIncompleteBody: "Plačila za to naročilo nismo prejeli pravočasno, zato je bilo samodejno preklicano. Če je bila na vaši kartici ali PayPalu rezervacija zneska, bo sproščena — ni vam bilo zaračunano nič. Novo naročilo lahko oddate, kadar koli ste pripravljeni.",
  },
  sr: {
    leaveConfirmTitle: "Изаћи без плаћања?",
    leaveConfirmBody: "Ако се сада вратите, ова наруџбина ће бити отказана — неће вам бити ништа наплаћено.",
    leaveConfirmStay: "Настави са плаћањем",
    leaveConfirmCancel: "Откажи моју наруџбину",
    paymentInProgressWarning: "Ваше плаћање се обрађује — молимо не затварајте ову страницу.",
    cancelUnpaidFailed: "Наруџбину није било могуће отказати. Покушајте поново.",
    cancelledPaymentIncompleteTitle: "Наруџбина отказана — плаћање није завршено",
    cancelledPaymentIncompleteBody: "Нисмо на време примили уплату за ову наруџбину, па је аутоматски отказана. Ако је на вашој картици или PayPal-у била резервација износа, биће ослобођена — ништа вам није наплаћено. Слободно наручите поново када будете спремни.",
  },
  sv: {
    leaveConfirmTitle: "Lämna utan att betala?",
    leaveConfirmBody: "Om du går tillbaka nu avbryts denna beställning — du debiteras ingenting.",
    leaveConfirmStay: "Fortsätt till betalning",
    leaveConfirmCancel: "Avbryt min beställning",
    paymentInProgressWarning: "Din betalning behandlas — stäng inte den här sidan.",
    cancelUnpaidFailed: "Det gick inte att avbryta beställningen. Försök igen.",
    cancelledPaymentIncompleteTitle: "Beställning avbruten — betalning slutfördes inte",
    cancelledPaymentIncompleteBody: "Vi tog inte emot betalning för denna beställning i tid, så den avbröts automatiskt. Om det fanns en reservation på ditt kort eller PayPal frigörs den — du har inte debiterats något. Lägg gärna en ny beställning när du är redo.",
  },
  th: {
    leaveConfirmTitle: "ออกโดยไม่ชำระเงิน?",
    leaveConfirmBody: "หากคุณย้อนกลับตอนนี้ คำสั่งซื้อนี้จะถูกยกเลิก — คุณจะไม่ถูกเรียกเก็บเงินใดๆ",
    leaveConfirmStay: "ดำเนินการชำระเงินต่อ",
    leaveConfirmCancel: "ยกเลิกคำสั่งซื้อของฉัน",
    paymentInProgressWarning: "การชำระเงินของคุณกำลังดำเนินการ — โปรดอย่าปิดหน้านี้",
    cancelUnpaidFailed: "ไม่สามารถยกเลิกคำสั่งซื้อได้ กรุณาลองอีกครั้ง",
    cancelledPaymentIncompleteTitle: "ยกเลิกคำสั่งซื้อแล้ว — การชำระเงินไม่สำเร็จ",
    cancelledPaymentIncompleteBody: "เราไม่ได้รับการชำระเงินสำหรับคำสั่งซื้อนี้ทันเวลา จึงถูกยกเลิกโดยอัตโนมัติ หากมีการกันวงเงินไว้บนบัตรหรือ PayPal ของคุณ จะถูกปลดล็อก — คุณไม่ถูกเรียกเก็บเงินใดๆ สามารถสั่งซื้อใหม่ได้ทุกเมื่อที่พร้อม",
  },
  tr: {
    leaveConfirmTitle: "Ödemeden çıkılsın mı?",
    leaveConfirmBody: "Şimdi geri dönerseniz bu sipariş iptal edilir — sizden herhangi bir ücret alınmaz.",
    leaveConfirmStay: "Ödemeye devam et",
    leaveConfirmCancel: "Siparişimi iptal et",
    paymentInProgressWarning: "Ödemeniz işleniyor — lütfen bu sayfayı kapatmayın.",
    cancelUnpaidFailed: "Sipariş iptal edilemedi. Lütfen tekrar deneyin.",
    cancelledPaymentIncompleteTitle: "Sipariş iptal edildi — ödeme tamamlanmadı",
    cancelledPaymentIncompleteBody: "Bu siparişin ödemesini zamanında alamadığımız için otomatik olarak iptal edildi. Kartınızda veya PayPal'ınızda bir bloke varsa serbest bırakılacaktır — sizden herhangi bir ücret alınmadı. Hazır olduğunuzda yeni bir sipariş verebilirsiniz.",
  },
  uk: {
    leaveConfirmTitle: "Вийти без оплати?",
    leaveConfirmBody: "Якщо ви повернетеся зараз, це замовлення буде скасовано — з вас нічого не спишуть.",
    leaveConfirmStay: "Продовжити оплату",
    leaveConfirmCancel: "Скасувати моє замовлення",
    paymentInProgressWarning: "Ваш платіж обробляється — будь ласка, не закривайте цю сторінку.",
    cancelUnpaidFailed: "Не вдалося скасувати замовлення. Спробуйте ще раз.",
    cancelledPaymentIncompleteTitle: "Замовлення скасовано — оплату не завершено",
    cancelledPaymentIncompleteBody: "Ми не отримали оплату за це замовлення вчасно, тому його було автоматично скасовано. Якщо на вашій картці або PayPal було утримання коштів, воно буде знято — з вас нічого не списано. Ви можете оформити нове замовлення, коли будете готові.",
  },
  vi: {
    leaveConfirmTitle: "Rời đi mà không thanh toán?",
    leaveConfirmBody: "Nếu bạn quay lại bây giờ, đơn hàng này sẽ bị hủy — bạn sẽ không bị tính phí.",
    leaveConfirmStay: "Tiếp tục thanh toán",
    leaveConfirmCancel: "Hủy đơn hàng của tôi",
    paymentInProgressWarning: "Khoản thanh toán của bạn đang được xử lý — vui lòng không đóng trang này.",
    cancelUnpaidFailed: "Không thể hủy đơn hàng. Vui lòng thử lại.",
    cancelledPaymentIncompleteTitle: "Đơn hàng đã bị hủy — thanh toán chưa hoàn tất",
    cancelledPaymentIncompleteBody: "Chúng tôi không nhận được thanh toán cho đơn hàng này kịp thời, vì vậy đơn hàng đã tự động bị hủy. Nếu có khoản tạm giữ trên thẻ hoặc PayPal của bạn, khoản đó sẽ được giải phóng — bạn chưa bị tính phí. Vui lòng đặt đơn hàng mới bất cứ khi nào bạn sẵn sàng.",
  },
  zh: {
    leaveConfirmTitle: "不付款就离开吗？",
    leaveConfirmBody: "现在返回将取消此订单 — 不会向您收取任何费用。",
    leaveConfirmStay: "继续付款",
    leaveConfirmCancel: "取消我的订单",
    paymentInProgressWarning: "您的付款正在处理中 — 请不要关闭此页面。",
    cancelUnpaidFailed: "无法取消订单，请重试。",
    cancelledPaymentIncompleteTitle: "订单已取消 — 付款未完成",
    cancelledPaymentIncompleteBody: "我们未能及时收到此订单的付款，因此已自动取消。如果您的卡或PayPal上有任何预留金额，将被释放 — 您未被收取任何费用。准备好后，欢迎随时下新订单。",
  },
};

for (const locale of ["en", ...LOCALES]) {
  const path = `src/messages/${locale}.json`;
  const data = JSON.parse(readFileSync(path, "utf8"));
  const trans = translations[locale] || translations.en;

  if (!data.customer) data.customer = {};
  if (!data.customer.payment) data.customer.payment = {};
  data.customer.payment.leaveConfirmTitle = trans.leaveConfirmTitle;
  data.customer.payment.leaveConfirmBody = trans.leaveConfirmBody;
  data.customer.payment.leaveConfirmStay = trans.leaveConfirmStay;
  data.customer.payment.leaveConfirmCancel = trans.leaveConfirmCancel;
  data.customer.payment.paymentInProgressWarning = trans.paymentInProgressWarning;
  data.customer.payment.cancelUnpaidFailed = trans.cancelUnpaidFailed;

  if (!data.email) data.email = {};
  if (!data.email.orderStatus) data.email.orderStatus = {};
  data.email.orderStatus.cancelledPaymentIncompleteTitle = trans.cancelledPaymentIncompleteTitle;
  data.email.orderStatus.cancelledPaymentIncompleteBody = trans.cancelledPaymentIncompleteBody;

  writeFileSync(path, JSON.stringify(data, null, 2) + "\n", "utf8");
  console.log(locale);
}
console.log("done");
