/**
 * Replaces the ENGLISH STUB values of `reseller.ordersList.*` with real
 * translations in all 37 non-English locales.
 *
 * Why this was needed: the keys were spliced into every locale file as copies of
 * the English text. The parity audit counts KEYS, not content, so it reported
 * "0 missing" while `admin.phoneOrderingPage.config` was 100% English in all 37
 * locales and this namespace 94–97%. Structurally done, substantively not.
 * Luigi 2026-08-09.
 *
 * These keys are live: /reseller/orders, /superadmin/orders and
 * /api/reseller/orders/[id] all call getTranslations("reseller.ordersList").
 *
 * ICU note: `countLabel` carries a plural. Each locale gets the CLDR categories
 * it actually needs — "other"-only for id/ja/ko/th/vi/zh, one/few/many for the
 * Slavic set, the full six for Arabic. `#` and {range} must survive.
 *
 *   npx tsx scripts/i18n-translate-reseller-orders-list.ts           (dry run)
 *   npx tsx scripts/i18n-translate-reseller-orders-list.ts --write
 */
import fs from "node:fs";
import path from "node:path";

const WRITE = process.argv.includes("--write");
const DIR = path.join(process.cwd(), "src", "messages");
const NS = ["reseller", "ordersList"];

type Pack = Record<string, string>;

const PACKS: Record<string, Pack> = {
  ar: { pageTitle: "قائمة الطلبات", pageTitlePlatform: "قائمة الطلبات — جميع المطاعم", countLabel: "{count, plural, zero {# نتيجة} one {# نتيجة} two {نتيجتان} few {# نتائج} many {# نتيجة} other {# نتيجة}} · {range}", searchPlaceholder: "ابحث بالاسم أو رقم الطلب أو الهاتف أو البريد…", colRestaurant: "المطعم", colCustomer: "العميل", colCompany: "اسم الشركة", colOrderId: "رقم الطلب", colPlacedAt: "وقت الطلب", colPayment: "طريقة الدفع", colFulfilment: "وقت التنفيذ", columns: "الأعمدة", allRestaurants: "جميع المطاعم.", allTypes: "جميع الأنواع", notApplicable: "غير متاح", type_delivery: "توصيل", type_pickup: "استلام", type_on_premise: "في المطعم", type_catering: "تقديم طعام", type_table_reservation: "حجز طاولة", type_reservation_preorder: "حجز وطلب مسبق", tabDetail: "تفاصيل الطلب", tabItems: "أصناف الطلب", showLess: "عرض أقل", lblConfirmedAt: "تم التأكيد في", lblFulfilledAt: "تم التنفيذ في", lblCredit: "رصيد المتجر", lblGuests: "الضيوف", lblDeposit: "العربون", lblPreOrder: "طلب مسبق", lblCode: "رمز التأكيد", loadError: "تعذّر تحميل هذا الطلب. يرجى المحاولة مرة أخرى.", export: "تصدير", showOlder: "عرض الطلبات الأقدم من 30 يومًا", narrowRange: "لقد وصلت إلى أقصى ما يمكن تصفحه دفعة واحدة. ضيّق النطاق الزمني، أو صفِّ حسب المطعم أو النوع، لعرض المزيد.", mixedCurrencyNote: "تستخدم مطاعمك أكثر من عملة واحدة، لذا يظهر كل إجمالي بعملة مطعمه الخاص ولا تُجمع الإجماليات معًا مطلقًا." },
  bg: { pageTitle: "Списък с поръчки", pageTitlePlatform: "Списък с поръчки — всички ресторанти", countLabel: "{count, plural, one {# резултат} other {# резултата}} · {range}", searchPlaceholder: "Търсене по име, номер на поръчка, телефон, имейл…", colRestaurant: "Ресторант", colCustomer: "Клиент", colCompany: "Име на фирма", colOrderId: "Номер на поръчка", colPlacedAt: "Направена на", colPayment: "Начин на плащане", colFulfilment: "Време на изпълнение", columns: "Колони", allRestaurants: "Всички ресторанти.", allTypes: "Всички типове", notApplicable: "Няма", type_delivery: "Доставка", type_pickup: "Вземане", type_on_premise: "На място", type_catering: "Кетъринг", type_table_reservation: "Резервация на маса", type_reservation_preorder: "Резервация и предварителна поръчка", tabDetail: "Детайли за поръчката", tabItems: "Артикули в поръчката", showLess: "Покажи по-малко", lblConfirmedAt: "Потвърдена на", lblFulfilledAt: "Изпълнена на", lblCredit: "Кредит в магазина", lblGuests: "Гости", lblDeposit: "Депозит", lblPreOrder: "Предварителна поръчка", lblCode: "Код за потвърждение", loadError: "Поръчката не можа да се зареди. Моля, опитайте отново.", export: "Експорт", showOlder: "Покажи поръчки по-стари от 30 дни", narrowRange: "Достигнахте максимума, който можем да покажем наведнъж. Стеснете периода или филтрирайте по ресторант или тип, за да видите повече.", mixedCurrencyNote: "Вашите ресторанти използват повече от една валута, затова всяка сума се показва във валутата на съответния ресторант и сумите никога не се събират." },
  ca: { pageTitle: "Llista de comandes", pageTitlePlatform: "Llista de comandes — Tots els restaurants", countLabel: "{count, plural, one {# resultat} other {# resultats}} · {range}", searchPlaceholder: "Cerca per nom, ID de comanda, telèfon, correu…", colRestaurant: "Restaurant", colCustomer: "Client", colCompany: "Nom de l'empresa", colOrderId: "ID de comanda", colPlacedAt: "Feta el", colPayment: "Mètode de pagament", colFulfilment: "Hora de lliurament", columns: "Columnes", allRestaurants: "Tots els restaurants.", allTypes: "Tots els tipus", notApplicable: "N/D", type_delivery: "Lliurament", type_pickup: "Recollida", type_on_premise: "Al local", type_catering: "Càtering", type_table_reservation: "Reserva de taula", type_reservation_preorder: "Reserva i comanda anticipada", tabDetail: "Detall de la comanda", tabItems: "Articles de la comanda", showLess: "Mostra'n menys", lblConfirmedAt: "Confirmada el", lblFulfilledAt: "Lliurada el", lblCredit: "Crèdit de la botiga", lblGuests: "Comensals", lblDeposit: "Dipòsit", lblPreOrder: "Comanda anticipada", lblCode: "Codi de confirmació", loadError: "No s'ha pogut carregar aquesta comanda. Torna-ho a provar.", export: "Exporta", showOlder: "Mostra comandes de fa més de 30 dies", narrowRange: "Has arribat al límit del que podem paginar de cop. Redueix l'interval de dates, o filtra per restaurant o tipus, per veure'n més.", mixedCurrencyNote: "Els teus restaurants utilitzen més d'una moneda, així que cada total es mostra en la moneda del seu restaurant i els totals mai no se sumen." },
  cs: { pageTitle: "Seznam objednávek", pageTitlePlatform: "Seznam objednávek — všechny restaurace", countLabel: "{count, plural, one {# výsledek} few {# výsledky} many {# výsledku} other {# výsledků}} · {range}", searchPlaceholder: "Hledat jméno, číslo objednávky, telefon, e-mail…", colRestaurant: "Restaurace", colCustomer: "Zákazník", colCompany: "Název firmy", colOrderId: "Číslo objednávky", colPlacedAt: "Vytvořeno", colPayment: "Způsob platby", colFulfilment: "Čas vyřízení", columns: "Sloupce", allRestaurants: "Všechny restaurace.", allTypes: "Všechny typy", notApplicable: "—", type_delivery: "Rozvoz", type_pickup: "Vyzvednutí", type_on_premise: "Na místě", type_catering: "Catering", type_table_reservation: "Rezervace stolu", type_reservation_preorder: "Rezervace a předobjednávka", tabDetail: "Detail objednávky", tabItems: "Položky objednávky", showLess: "Zobrazit méně", lblConfirmedAt: "Potvrzeno", lblFulfilledAt: "Vyřízeno", lblCredit: "Kredit v podniku", lblGuests: "Hosté", lblDeposit: "Záloha", lblPreOrder: "Předobjednávka", lblCode: "Potvrzovací kód", loadError: "Objednávku se nepodařilo načíst. Zkuste to prosím znovu.", export: "Exportovat", showOlder: "Zobrazit objednávky starší 30 dnů", narrowRange: "Dosáhli jste maxima, které lze najednou zobrazit. Zužte časové období nebo filtrujte podle restaurace či typu.", mixedCurrencyNote: "Vaše restaurace používají více měn, proto se každý součet zobrazuje v měně dané restaurace a součty se nikdy nesčítají dohromady." },
  da: { pageTitle: "Ordreliste", pageTitlePlatform: "Ordreliste — alle restauranter", countLabel: "{count, plural, one {# resultat} other {# resultater}} · {range}", searchPlaceholder: "Søg navn, ordre-id, telefon, e-mail…", colRestaurant: "Restaurant", colCustomer: "Kunde", colCompany: "Firmanavn", colOrderId: "Ordre-id", colPlacedAt: "Afgivet", colPayment: "Betalingsmetode", colFulfilment: "Leveringstidspunkt", columns: "Kolonner", allRestaurants: "Alle restauranter.", allTypes: "Alle typer", notApplicable: "—", type_delivery: "Levering", type_pickup: "Afhentning", type_on_premise: "På stedet", type_catering: "Catering", type_table_reservation: "Bordreservation", type_reservation_preorder: "Reservation og forudbestilling", tabDetail: "Ordredetaljer", tabItems: "Ordrelinjer", showLess: "Vis mindre", lblConfirmedAt: "Bekræftet", lblFulfilledAt: "Leveret", lblCredit: "Butikskredit", lblGuests: "Gæster", lblDeposit: "Depositum", lblPreOrder: "Forudbestilling", lblCode: "Bekræftelseskode", loadError: "Ordren kunne ikke indlæses. Prøv igen.", export: "Eksportér", showOlder: "Vis ordrer ældre end 30 dage", narrowRange: "Du har nået så langt, vi kan bladre på én gang. Indsnævr datointervallet, eller filtrér efter restaurant eller type, for at se mere.", mixedCurrencyNote: "Dine restauranter bruger mere end én valuta, så hver total vises i sin egen restaurants valuta, og totaler lægges aldrig sammen." },
  de: { pageTitle: "Bestellliste", pageTitlePlatform: "Bestellliste — Alle Restaurants", countLabel: "{count, plural, one {# Ergebnis} other {# Ergebnisse}} · {range}", searchPlaceholder: "Name, Bestell-ID, Telefon, E-Mail suchen…", colRestaurant: "Restaurant", colCustomer: "Kunde", colCompany: "Firmenname", colOrderId: "Bestell-ID", colPlacedAt: "Aufgegeben am", colPayment: "Zahlungsart", colFulfilment: "Ausführungszeit", columns: "Spalten", allRestaurants: "Alle Restaurants.", allTypes: "Alle Typen", notApplicable: "—", type_delivery: "Lieferung", type_pickup: "Abholung", type_on_premise: "Vor Ort", type_catering: "Catering", type_table_reservation: "Tischreservierung", type_reservation_preorder: "Reservierung & Vorbestellung", tabDetail: "Bestelldetails", tabItems: "Bestellpositionen", showLess: "Weniger anzeigen", lblConfirmedAt: "Bestätigt am", lblFulfilledAt: "Ausgeführt am", lblCredit: "Guthaben", lblGuests: "Gäste", lblDeposit: "Anzahlung", lblPreOrder: "Vorbestellung", lblCode: "Bestätigungscode", loadError: "Diese Bestellung konnte nicht geladen werden. Bitte erneut versuchen.", export: "Exportieren", showOlder: "Bestellungen älter als 30 Tage anzeigen", narrowRange: "Weiter können wir nicht auf einmal blättern. Schränken Sie den Zeitraum ein oder filtern Sie nach Restaurant oder Typ, um mehr zu sehen.", mixedCurrencyNote: "Ihre Restaurants verwenden mehrere Währungen. Jede Summe wird daher in der Währung des jeweiligen Restaurants angezeigt und Summen werden nie addiert." },
  el: { pageTitle: "Λίστα παραγγελιών", pageTitlePlatform: "Λίστα παραγγελιών — Όλα τα εστιατόρια", countLabel: "{count, plural, one {# αποτέλεσμα} other {# αποτελέσματα}} · {range}", searchPlaceholder: "Αναζήτηση ονόματος, κωδικού παραγγελίας, τηλεφώνου, email…", colRestaurant: "Εστιατόριο", colCustomer: "Πελάτης", colCompany: "Επωνυμία εταιρείας", colOrderId: "Κωδικός παραγγελίας", colPlacedAt: "Καταχωρήθηκε", colPayment: "Τρόπος πληρωμής", colFulfilment: "Ώρα εκτέλεσης", columns: "Στήλες", allRestaurants: "Όλα τα εστιατόρια.", allTypes: "Όλοι οι τύποι", notApplicable: "—", type_delivery: "Παράδοση", type_pickup: "Παραλαβή", type_on_premise: "Στο κατάστημα", type_catering: "Catering", type_table_reservation: "Κράτηση τραπεζιού", type_reservation_preorder: "Κράτηση & προπαραγγελία", tabDetail: "Λεπτομέρειες παραγγελίας", tabItems: "Είδη παραγγελίας", showLess: "Εμφάνιση λιγότερων", lblConfirmedAt: "Επιβεβαιώθηκε", lblFulfilledAt: "Εκτελέστηκε", lblCredit: "Πίστωση καταστήματος", lblGuests: "Άτομα", lblDeposit: "Προκαταβολή", lblPreOrder: "Προπαραγγελία", lblCode: "Κωδικός επιβεβαίωσης", loadError: "Δεν ήταν δυνατή η φόρτωση της παραγγελίας. Δοκιμάστε ξανά.", export: "Εξαγωγή", showOlder: "Εμφάνιση παραγγελιών παλαιότερων των 30 ημερών", narrowRange: "Φτάσατε στο όριο όσων μπορούμε να εμφανίσουμε με τη μία. Περιορίστε το εύρος ημερομηνιών ή φιλτράρετε ανά εστιατόριο ή τύπο.", mixedCurrencyNote: "Τα εστιατόριά σας χρησιμοποιούν περισσότερα από ένα νομίσματα, γι' αυτό κάθε σύνολο εμφανίζεται στο νόμισμα του δικού του εστιατορίου και τα σύνολα δεν αθροίζονται ποτέ." },
  es: { pageTitle: "Lista de pedidos", pageTitlePlatform: "Lista de pedidos — Todos los restaurantes", countLabel: "{count, plural, one {# resultado} other {# resultados}} · {range}", searchPlaceholder: "Buscar nombre, ID de pedido, teléfono, correo…", colRestaurant: "Restaurante", colCustomer: "Cliente", colCompany: "Nombre de la empresa", colOrderId: "ID de pedido", colPlacedAt: "Realizado el", colPayment: "Método de pago", colFulfilment: "Hora de entrega", columns: "Columnas", allRestaurants: "Todos los restaurantes.", allTypes: "Todos los tipos", notApplicable: "N/D", type_delivery: "Entrega", type_pickup: "Recogida", type_on_premise: "En el local", type_catering: "Catering", type_table_reservation: "Reserva de mesa", type_reservation_preorder: "Reserva y pedido anticipado", tabDetail: "Detalle del pedido", tabItems: "Artículos del pedido", showLess: "Mostrar menos", lblConfirmedAt: "Confirmado el", lblFulfilledAt: "Entregado el", lblCredit: "Crédito de la tienda", lblGuests: "Comensales", lblDeposit: "Depósito", lblPreOrder: "Pedido anticipado", lblCode: "Código de confirmación", loadError: "No se pudo cargar este pedido. Inténtalo de nuevo.", export: "Exportar", showOlder: "Mostrar pedidos de más de 30 días", narrowRange: "Has llegado al máximo que podemos paginar de una vez. Reduce el intervalo de fechas, o filtra por restaurante o tipo, para ver más.", mixedCurrencyNote: "Tus restaurantes usan más de una moneda, por lo que cada total se muestra en la moneda de su propio restaurante y los totales nunca se suman." },
  et: { pageTitle: "Tellimuste loend", pageTitlePlatform: "Tellimuste loend — kõik restoranid", countLabel: "{count, plural, one {# tulemus} other {# tulemust}} · {range}", searchPlaceholder: "Otsi nime, tellimuse ID-d, telefoni, e-posti…", colRestaurant: "Restoran", colCustomer: "Klient", colCompany: "Ettevõtte nimi", colOrderId: "Tellimuse ID", colPlacedAt: "Esitatud", colPayment: "Makseviis", colFulfilment: "Täitmise aeg", columns: "Veerud", allRestaurants: "Kõik restoranid.", allTypes: "Kõik tüübid", notApplicable: "—", type_delivery: "Kohaletoimetamine", type_pickup: "Järeletulek", type_on_premise: "Kohapeal", type_catering: "Toitlustus", type_table_reservation: "Laua broneering", type_reservation_preorder: "Broneering ja ettetellimus", tabDetail: "Tellimuse üksikasjad", tabItems: "Tellimuse read", showLess: "Näita vähem", lblConfirmedAt: "Kinnitatud", lblFulfilledAt: "Täidetud", lblCredit: "Poekrediit", lblGuests: "Külalised", lblDeposit: "Ettemaks", lblPreOrder: "Ettetellimus", lblCode: "Kinnituskood", loadError: "Selle tellimuse laadimine ebaõnnestus. Palun proovi uuesti.", export: "Ekspordi", showOlder: "Näita üle 30 päeva vanuseid tellimusi", narrowRange: "Olete jõudnud nii kaugele, kui korraga sirvida saab. Kitsendage ajavahemikku või filtreerige restorani või tüübi järgi.", mixedCurrencyNote: "Teie restoranid kasutavad mitut valuutat, seega kuvatakse iga summa oma restorani valuutas ja summasid ei liideta kunagi kokku." },
  fi: { pageTitle: "Tilauslista", pageTitlePlatform: "Tilauslista — kaikki ravintolat", countLabel: "{count, plural, one {# tulos} other {# tulosta}} · {range}", searchPlaceholder: "Hae nimi, tilaustunnus, puhelin, sähköposti…", colRestaurant: "Ravintola", colCustomer: "Asiakas", colCompany: "Yrityksen nimi", colOrderId: "Tilaustunnus", colPlacedAt: "Tehty", colPayment: "Maksutapa", colFulfilment: "Toimitusaika", columns: "Sarakkeet", allRestaurants: "Kaikki ravintolat.", allTypes: "Kaikki tyypit", notApplicable: "—", type_delivery: "Kuljetus", type_pickup: "Nouto", type_on_premise: "Paikan päällä", type_catering: "Pitopalvelu", type_table_reservation: "Pöytävaraus", type_reservation_preorder: "Varaus ja ennakkotilaus", tabDetail: "Tilauksen tiedot", tabItems: "Tilausrivit", showLess: "Näytä vähemmän", lblConfirmedAt: "Vahvistettu", lblFulfilledAt: "Toimitettu", lblCredit: "Myymäläkredit", lblGuests: "Vieraat", lblDeposit: "Ennakkomaksu", lblPreOrder: "Ennakkotilaus", lblCode: "Vahvistuskoodi", loadError: "Tilauksen lataaminen epäonnistui. Yritä uudelleen.", export: "Vie", showOlder: "Näytä yli 30 päivää vanhat tilaukset", narrowRange: "Olet saavuttanut rajan, jonka voimme selata kerralla. Rajaa aikaväliä tai suodata ravintolan tai tyypin mukaan nähdäksesi lisää.", mixedCurrencyNote: "Ravintoloissasi on käytössä useampi valuutta, joten jokainen summa näytetään oman ravintolansa valuutassa eikä summia lasketa koskaan yhteen." },
  fr: { pageTitle: "Liste des commandes", pageTitlePlatform: "Liste des commandes — Tous les restaurants", countLabel: "{count, plural, one {# résultat} other {# résultats}} · {range}", searchPlaceholder: "Rechercher un nom, un n° de commande, un téléphone, un e-mail…", colRestaurant: "Restaurant", colCustomer: "Client", colCompany: "Nom de l'entreprise", colOrderId: "N° de commande", colPlacedAt: "Passée le", colPayment: "Moyen de paiement", colFulfilment: "Heure d'exécution", columns: "Colonnes", allRestaurants: "Tous les restaurants.", allTypes: "Tous les types", notApplicable: "N/D", type_delivery: "Livraison", type_pickup: "À emporter", type_on_premise: "Sur place", type_catering: "Traiteur", type_table_reservation: "Réservation de table", type_reservation_preorder: "Réservation et précommande", tabDetail: "Détail de la commande", tabItems: "Articles de la commande", showLess: "Afficher moins", lblConfirmedAt: "Confirmée le", lblFulfilledAt: "Exécutée le", lblCredit: "Crédit boutique", lblGuests: "Couverts", lblDeposit: "Acompte", lblPreOrder: "Précommande", lblCode: "Code de confirmation", loadError: "Impossible de charger cette commande. Veuillez réessayer.", export: "Exporter", showOlder: "Afficher les commandes de plus de 30 jours", narrowRange: "Vous avez atteint la limite de ce que nous pouvons parcourir en une fois. Réduisez la plage de dates, ou filtrez par restaurant ou type, pour en voir plus.", mixedCurrencyNote: "Vos restaurants utilisent plusieurs devises : chaque total est donc affiché dans la devise de son propre restaurant et les totaux ne sont jamais additionnés." },
  he: { pageTitle: "רשימת הזמנות", pageTitlePlatform: "רשימת הזמנות — כל המסעדות", countLabel: "{count, plural, one {תוצאה אחת} two {# תוצאות} many {# תוצאות} other {# תוצאות}} · {range}", searchPlaceholder: "חיפוש שם, מספר הזמנה, טלפון, אימייל…", colRestaurant: "מסעדה", colCustomer: "לקוח", colCompany: "שם החברה", colOrderId: "מספר הזמנה", colPlacedAt: "הוזמנה ב", colPayment: "אמצעי תשלום", colFulfilment: "שעת ביצוע", columns: "עמודות", allRestaurants: "כל המסעדות.", allTypes: "כל הסוגים", notApplicable: "—", type_delivery: "משלוח", type_pickup: "איסוף עצמי", type_on_premise: "במקום", type_catering: "קייטרינג", type_table_reservation: "הזמנת שולחן", type_reservation_preorder: "הזמנת שולחן והזמנה מראש", tabDetail: "פרטי ההזמנה", tabItems: "פריטי ההזמנה", showLess: "הצג פחות", lblConfirmedAt: "אושרה ב", lblFulfilledAt: "הושלמה ב", lblCredit: "קרדיט בחנות", lblGuests: "סועדים", lblDeposit: "מקדמה", lblPreOrder: "הזמנה מראש", lblCode: "קוד אישור", loadError: "לא ניתן לטעון את ההזמנה הזו. נסה שוב.", export: "ייצוא", showOlder: "הצג הזמנות מלפני יותר מ-30 יום", narrowRange: "הגעת לגבול שאנחנו יכולים לדפדף בבת אחת. צמצם את טווח התאריכים, או סנן לפי מסעדה או סוג, כדי לראות עוד.", mixedCurrencyNote: "המסעדות שלך משתמשות ביותר ממטבע אחד, ולכן כל סכום מוצג במטבע של המסעדה שלו והסכומים לעולם אינם מחוברים יחד." },
  hi: { pageTitle: "ऑर्डर सूची", pageTitlePlatform: "ऑर्डर सूची — सभी रेस्टोरेंट", countLabel: "{count, plural, one {# परिणाम} other {# परिणाम}} · {range}", searchPlaceholder: "नाम, ऑर्डर आईडी, फ़ोन, ईमेल खोजें…", colRestaurant: "रेस्टोरेंट", colCustomer: "ग्राहक", colCompany: "कंपनी का नाम", colOrderId: "ऑर्डर आईडी", colPlacedAt: "दिया गया", colPayment: "भुगतान का तरीका", colFulfilment: "पूर्ति समय", columns: "कॉलम", allRestaurants: "सभी रेस्टोरेंट।", allTypes: "सभी प्रकार", notApplicable: "लागू नहीं", type_delivery: "डिलीवरी", type_pickup: "पिकअप", type_on_premise: "परिसर में", type_catering: "कैटरिंग", type_table_reservation: "टेबल आरक्षण", type_reservation_preorder: "आरक्षण और प्री-ऑर्डर", tabDetail: "ऑर्डर विवरण", tabItems: "ऑर्डर आइटम", showLess: "कम दिखाएँ", lblConfirmedAt: "पुष्टि हुई", lblFulfilledAt: "पूरा हुआ", lblCredit: "स्टोर क्रेडिट", lblGuests: "मेहमान", lblDeposit: "जमा राशि", lblPreOrder: "प्री-ऑर्डर", lblCode: "पुष्टिकरण कोड", loadError: "यह ऑर्डर लोड नहीं हो सका। कृपया फिर से प्रयास करें।", export: "निर्यात", showOlder: "30 दिन से पुराने ऑर्डर दिखाएँ", narrowRange: "आप उतना देख चुके हैं जितना हम एक बार में दिखा सकते हैं। और देखने के लिए तिथि सीमा घटाएँ, या रेस्टोरेंट या प्रकार से फ़िल्टर करें।", mixedCurrencyNote: "आपके रेस्टोरेंट एक से अधिक मुद्राओं का उपयोग करते हैं, इसलिए प्रत्येक कुल अपने रेस्टोरेंट की मुद्रा में दिखाया जाता है और कुल कभी नहीं जोड़े जाते।" },
  hr: { pageTitle: "Popis narudžbi", pageTitlePlatform: "Popis narudžbi — svi restorani", countLabel: "{count, plural, one {# rezultat} few {# rezultata} other {# rezultata}} · {range}", searchPlaceholder: "Pretraži ime, broj narudžbe, telefon, e-poštu…", colRestaurant: "Restoran", colCustomer: "Kupac", colCompany: "Naziv tvrtke", colOrderId: "Broj narudžbe", colPlacedAt: "Zaprimljeno", colPayment: "Način plaćanja", colFulfilment: "Vrijeme izvršenja", columns: "Stupci", allRestaurants: "Svi restorani.", allTypes: "Sve vrste", notApplicable: "—", type_delivery: "Dostava", type_pickup: "Preuzimanje", type_on_premise: "U lokalu", type_catering: "Catering", type_table_reservation: "Rezervacija stola", type_reservation_preorder: "Rezervacija i prednarudžba", tabDetail: "Detalji narudžbe", tabItems: "Stavke narudžbe", showLess: "Prikaži manje", lblConfirmedAt: "Potvrđeno", lblFulfilledAt: "Izvršeno", lblCredit: "Kredit u lokalu", lblGuests: "Gosti", lblDeposit: "Polog", lblPreOrder: "Prednarudžba", lblCode: "Kod potvrde", loadError: "Nije moguće učitati ovu narudžbu. Pokušajte ponovno.", export: "Izvezi", showOlder: "Prikaži narudžbe starije od 30 dana", narrowRange: "Došli ste do granice koju možemo prikazati odjednom. Suzite raspon datuma ili filtrirajte po restoranu ili vrsti.", mixedCurrencyNote: "Vaši restorani koriste više od jedne valute, pa se svaki iznos prikazuje u valuti svog restorana i iznosi se nikada ne zbrajaju." },
  hu: { pageTitle: "Rendelési lista", pageTitlePlatform: "Rendelési lista — Összes étterem", countLabel: "{count, plural, one {# találat} other {# találat}} · {range}", searchPlaceholder: "Keresés név, rendelésszám, telefon, e-mail alapján…", colRestaurant: "Étterem", colCustomer: "Vendég", colCompany: "Cégnév", colOrderId: "Rendelésszám", colPlacedAt: "Leadva", colPayment: "Fizetési mód", colFulfilment: "Teljesítés ideje", columns: "Oszlopok", allRestaurants: "Összes étterem.", allTypes: "Összes típus", notApplicable: "—", type_delivery: "Kiszállítás", type_pickup: "Elvitel", type_on_premise: "Helyben", type_catering: "Catering", type_table_reservation: "Asztalfoglalás", type_reservation_preorder: "Foglalás és előrendelés", tabDetail: "Rendelés részletei", tabItems: "Rendelés tételei", showLess: "Kevesebb megjelenítése", lblConfirmedAt: "Visszaigazolva", lblFulfilledAt: "Teljesítve", lblCredit: "Üzleti kredit", lblGuests: "Vendégek", lblDeposit: "Előleg", lblPreOrder: "Előrendelés", lblCode: "Visszaigazoló kód", loadError: "A rendelést nem sikerült betölteni. Kérjük, próbálja újra.", export: "Exportálás", showOlder: "30 napnál régebbi rendelések megjelenítése", narrowRange: "Elérte azt a határt, ameddig egyszerre lapozhatunk. Szűkítse az időszakot, vagy szűrjön étteremre vagy típusra, hogy többet lásson.", mixedCurrencyNote: "Éttermei többféle pénznemet használnak, ezért minden összeg a saját éttermének pénznemében jelenik meg, és az összegeket soha nem adjuk össze." },
  id: { pageTitle: "Daftar Pesanan", pageTitlePlatform: "Daftar Pesanan — Semua Restoran", countLabel: "{count, plural, other {# hasil}} · {range}", searchPlaceholder: "Cari nama, ID pesanan, telepon, email…", colRestaurant: "Restoran", colCustomer: "Pelanggan", colCompany: "Nama Perusahaan", colOrderId: "ID Pesanan", colPlacedAt: "Dibuat pada", colPayment: "Metode Pembayaran", colFulfilment: "Waktu pemenuhan", columns: "Kolom", allRestaurants: "Semua restoran.", allTypes: "Semua jenis", notApplicable: "—", type_delivery: "Pengantaran", type_pickup: "Ambil sendiri", type_on_premise: "Di tempat", type_catering: "Katering", type_table_reservation: "Reservasi meja", type_reservation_preorder: "Reservasi & pra-pesan", tabDetail: "Detail pesanan", tabItems: "Item pesanan", showLess: "Tampilkan lebih sedikit", lblConfirmedAt: "Dikonfirmasi pada", lblFulfilledAt: "Dipenuhi pada", lblCredit: "Kredit toko", lblGuests: "Tamu", lblDeposit: "Deposit", lblPreOrder: "Pra-pesan", lblCode: "Kode konfirmasi", loadError: "Tidak dapat memuat pesanan ini. Silakan coba lagi.", export: "Ekspor", showOlder: "Tampilkan pesanan lebih dari 30 hari", narrowRange: "Anda telah mencapai batas yang dapat kami tampilkan sekaligus. Persempit rentang tanggal, atau filter berdasarkan restoran atau jenis, untuk melihat lebih banyak.", mixedCurrencyNote: "Restoran Anda menggunakan lebih dari satu mata uang, jadi setiap total ditampilkan dalam mata uang restorannya sendiri dan total tidak pernah dijumlahkan." },
  it: { pageTitle: "Elenco ordini", pageTitlePlatform: "Elenco ordini — Tutti i ristoranti", countLabel: "{count, plural, one {# risultato} other {# risultati}} · {range}", searchPlaceholder: "Cerca nome, ID ordine, telefono, email…", colRestaurant: "Ristorante", colCustomer: "Cliente", colCompany: "Ragione sociale", colOrderId: "ID ordine", colPlacedAt: "Effettuato il", colPayment: "Metodo di pagamento", colFulfilment: "Orario di evasione", columns: "Colonne", allRestaurants: "Tutti i ristoranti.", allTypes: "Tutti i tipi", notApplicable: "N/D", type_delivery: "Consegna", type_pickup: "Ritiro", type_on_premise: "In loco", type_catering: "Catering", type_table_reservation: "Prenotazione tavolo", type_reservation_preorder: "Prenotazione e pre-ordine", tabDetail: "Dettaglio ordine", tabItems: "Articoli dell'ordine", showLess: "Mostra meno", lblConfirmedAt: "Confermato il", lblFulfilledAt: "Evaso il", lblCredit: "Credito del locale", lblGuests: "Ospiti", lblDeposit: "Caparra", lblPreOrder: "Pre-ordine", lblCode: "Codice di conferma", loadError: "Impossibile caricare questo ordine. Riprova.", export: "Esporta", showOlder: "Mostra ordini più vecchi di 30 giorni", narrowRange: "Hai raggiunto il limite di ciò che possiamo sfogliare in una volta. Restringi l'intervallo di date, o filtra per ristorante o tipo, per vederne altri.", mixedCurrencyNote: "I tuoi ristoranti usano più di una valuta, quindi ogni totale è mostrato nella valuta del proprio ristorante e i totali non vengono mai sommati." },
  ja: { pageTitle: "注文リスト", pageTitlePlatform: "注文リスト — 全店舗", countLabel: "{count, plural, other {#件の結果}} · {range}", searchPlaceholder: "名前、注文ID、電話番号、メールで検索…", colRestaurant: "店舗", colCustomer: "お客様", colCompany: "会社名", colOrderId: "注文ID", colPlacedAt: "注文日時", colPayment: "支払い方法", colFulfilment: "提供時刻", columns: "列", allRestaurants: "全店舗。", allTypes: "すべての種類", notApplicable: "該当なし", type_delivery: "配達", type_pickup: "テイクアウト", type_on_premise: "店内", type_catering: "ケータリング", type_table_reservation: "席の予約", type_reservation_preorder: "予約と事前注文", tabDetail: "注文詳細", tabItems: "注文商品", showLess: "折りたたむ", lblConfirmedAt: "確定日時", lblFulfilledAt: "完了日時", lblCredit: "ストアクレジット", lblGuests: "人数", lblDeposit: "デポジット", lblPreOrder: "事前注文", lblCode: "確認コード", loadError: "この注文を読み込めませんでした。もう一度お試しください。", export: "エクスポート", showOlder: "30日より前の注文を表示", narrowRange: "一度に表示できる上限に達しました。期間を絞り込むか、店舗や種類で絞り込んでください。", mixedCurrencyNote: "複数の通貨を使用する店舗があるため、各合計はその店舗の通貨で表示され、合計同士が合算されることはありません。" },
  ko: { pageTitle: "주문 목록", pageTitlePlatform: "주문 목록 — 전체 매장", countLabel: "{count, plural, other {결과 #건}} · {range}", searchPlaceholder: "이름, 주문 ID, 전화번호, 이메일 검색…", colRestaurant: "매장", colCustomer: "고객", colCompany: "회사명", colOrderId: "주문 ID", colPlacedAt: "주문 시각", colPayment: "결제 수단", colFulfilment: "완료 시각", columns: "열", allRestaurants: "전체 매장.", allTypes: "전체 유형", notApplicable: "해당 없음", type_delivery: "배달", type_pickup: "포장", type_on_premise: "매장 내", type_catering: "케이터링", type_table_reservation: "좌석 예약", type_reservation_preorder: "예약 및 사전 주문", tabDetail: "주문 상세", tabItems: "주문 항목", showLess: "간략히 보기", lblConfirmedAt: "확정 시각", lblFulfilledAt: "완료 시각", lblCredit: "매장 크레딧", lblGuests: "인원", lblDeposit: "예약금", lblPreOrder: "사전 주문", lblCode: "확인 코드", loadError: "이 주문을 불러오지 못했습니다. 다시 시도해 주세요.", export: "내보내기", showOlder: "30일 이전 주문 보기", narrowRange: "한 번에 조회할 수 있는 한도에 도달했습니다. 기간을 좁히거나 매장 또는 유형으로 필터링해 주세요.", mixedCurrencyNote: "매장마다 통화가 달라 각 합계는 해당 매장의 통화로 표시되며, 합계끼리 더해지지 않습니다." },
  lt: { pageTitle: "Užsakymų sąrašas", pageTitlePlatform: "Užsakymų sąrašas — visi restoranai", countLabel: "{count, plural, one {# rezultatas} few {# rezultatai} other {# rezultatų}} · {range}", searchPlaceholder: "Ieškoti vardo, užsakymo ID, telefono, el. pašto…", colRestaurant: "Restoranas", colCustomer: "Klientas", colCompany: "Įmonės pavadinimas", colOrderId: "Užsakymo ID", colPlacedAt: "Pateiktas", colPayment: "Mokėjimo būdas", colFulfilment: "Įvykdymo laikas", columns: "Stulpeliai", allRestaurants: "Visi restoranai.", allTypes: "Visi tipai", notApplicable: "—", type_delivery: "Pristatymas", type_pickup: "Atsiėmimas", type_on_premise: "Vietoje", type_catering: "Maitinimo paslaugos", type_table_reservation: "Staliuko rezervacija", type_reservation_preorder: "Rezervacija ir išankstinis užsakymas", tabDetail: "Užsakymo informacija", tabItems: "Užsakymo prekės", showLess: "Rodyti mažiau", lblConfirmedAt: "Patvirtinta", lblFulfilledAt: "Įvykdyta", lblCredit: "Parduotuvės kreditas", lblGuests: "Svečiai", lblDeposit: "Užstatas", lblPreOrder: "Išankstinis užsakymas", lblCode: "Patvirtinimo kodas", loadError: "Nepavyko įkelti šio užsakymo. Bandykite dar kartą.", export: "Eksportuoti", showOlder: "Rodyti senesnius nei 30 dienų užsakymus", narrowRange: "Pasiekėte ribą, kiek galime parodyti iš karto. Susiaurinkite datų intervalą arba filtruokite pagal restoraną ar tipą.", mixedCurrencyNote: "Jūsų restoranai naudoja daugiau nei vieną valiutą, todėl kiekviena suma rodoma savo restorano valiuta ir sumos niekada nesudedamos." },
  lv: { pageTitle: "Pasūtījumu saraksts", pageTitlePlatform: "Pasūtījumu saraksts — visi restorāni", countLabel: "{count, plural, zero {# rezultātu} one {# rezultāts} other {# rezultāti}} · {range}", searchPlaceholder: "Meklēt vārdu, pasūtījuma ID, tālruni, e-pastu…", colRestaurant: "Restorāns", colCustomer: "Klients", colCompany: "Uzņēmuma nosaukums", colOrderId: "Pasūtījuma ID", colPlacedAt: "Izveidots", colPayment: "Maksājuma veids", colFulfilment: "Izpildes laiks", columns: "Kolonnas", allRestaurants: "Visi restorāni.", allTypes: "Visi veidi", notApplicable: "—", type_delivery: "Piegāde", type_pickup: "Izņemšana", type_on_premise: "Uz vietas", type_catering: "Ēdināšana", type_table_reservation: "Galdiņa rezervācija", type_reservation_preorder: "Rezervācija un iepriekšpasūtījums", tabDetail: "Pasūtījuma informācija", tabItems: "Pasūtījuma pozīcijas", showLess: "Rādīt mazāk", lblConfirmedAt: "Apstiprināts", lblFulfilledAt: "Izpildīts", lblCredit: "Veikala kredīts", lblGuests: "Viesi", lblDeposit: "Depozīts", lblPreOrder: "Iepriekšpasūtījums", lblCode: "Apstiprinājuma kods", loadError: "Neizdevās ielādēt šo pasūtījumu. Lūdzu, mēģiniet vēlreiz.", export: "Eksportēt", showOlder: "Rādīt pasūtījumus, kas vecāki par 30 dienām", narrowRange: "Esat sasniedzis robežu, cik varam parādīt vienlaikus. Sašauriniet datumu diapazonu vai filtrējiet pēc restorāna vai veida.", mixedCurrencyNote: "Jūsu restorāni izmanto vairāk nekā vienu valūtu, tāpēc katra summa tiek rādīta sava restorāna valūtā un summas nekad netiek saskaitītas kopā." },
  nb: { pageTitle: "Ordreliste", pageTitlePlatform: "Ordreliste — alle restauranter", countLabel: "{count, plural, one {# resultat} other {# resultater}} · {range}", searchPlaceholder: "Søk navn, ordre-ID, telefon, e-post…", colRestaurant: "Restaurant", colCustomer: "Kunde", colCompany: "Firmanavn", colOrderId: "Ordre-ID", colPlacedAt: "Lagt inn", colPayment: "Betalingsmåte", colFulfilment: "Leveringstid", columns: "Kolonner", allRestaurants: "Alle restauranter.", allTypes: "Alle typer", notApplicable: "—", type_delivery: "Levering", type_pickup: "Henting", type_on_premise: "På stedet", type_catering: "Catering", type_table_reservation: "Bordreservasjon", type_reservation_preorder: "Reservasjon og forhåndsbestilling", tabDetail: "Ordredetaljer", tabItems: "Ordrelinjer", showLess: "Vis mindre", lblConfirmedAt: "Bekreftet", lblFulfilledAt: "Levert", lblCredit: "Butikkreditt", lblGuests: "Gjester", lblDeposit: "Depositum", lblPreOrder: "Forhåndsbestilling", lblCode: "Bekreftelseskode", loadError: "Kunne ikke laste denne ordren. Prøv igjen.", export: "Eksporter", showOlder: "Vis ordrer eldre enn 30 dager", narrowRange: "Du har nådd så langt vi kan bla på én gang. Snevre inn datoperioden, eller filtrer på restaurant eller type, for å se mer.", mixedCurrencyNote: "Restaurantene dine bruker mer enn én valuta, så hver sum vises i sin egen restaurants valuta og summer legges aldri sammen." },
  nl: { pageTitle: "Bestellijst", pageTitlePlatform: "Bestellijst — Alle restaurants", countLabel: "{count, plural, one {# resultaat} other {# resultaten}} · {range}", searchPlaceholder: "Zoek naam, bestel-ID, telefoon, e-mail…", colRestaurant: "Restaurant", colCustomer: "Klant", colCompany: "Bedrijfsnaam", colOrderId: "Bestel-ID", colPlacedAt: "Geplaatst op", colPayment: "Betaalmethode", colFulfilment: "Tijd van uitvoering", columns: "Kolommen", allRestaurants: "Alle restaurants.", allTypes: "Alle typen", notApplicable: "n.v.t.", type_delivery: "Bezorging", type_pickup: "Afhalen", type_on_premise: "Ter plaatse", type_catering: "Catering", type_table_reservation: "Tafelreservering", type_reservation_preorder: "Reservering en voorbestelling", tabDetail: "Bestelgegevens", tabItems: "Bestelregels", showLess: "Minder tonen", lblConfirmedAt: "Bevestigd op", lblFulfilledAt: "Uitgevoerd op", lblCredit: "Winkeltegoed", lblGuests: "Gasten", lblDeposit: "Aanbetaling", lblPreOrder: "Voorbestelling", lblCode: "Bevestigingscode", loadError: "Kan deze bestelling niet laden. Probeer het opnieuw.", export: "Exporteren", showOlder: "Bestellingen ouder dan 30 dagen tonen", narrowRange: "Je hebt het maximum bereikt van wat we in één keer kunnen tonen. Verklein het datumbereik, of filter op restaurant of type, om meer te zien.", mixedCurrencyNote: "Je restaurants gebruiken meer dan één valuta, dus elk totaal wordt getoond in de valuta van het eigen restaurant en totalen worden nooit bij elkaar opgeteld." },
  pl: { pageTitle: "Lista zamówień", pageTitlePlatform: "Lista zamówień — wszystkie restauracje", countLabel: "{count, plural, one {# wynik} few {# wyniki} many {# wyników} other {# wyniku}} · {range}", searchPlaceholder: "Szukaj nazwy, numeru zamówienia, telefonu, e-maila…", colRestaurant: "Restauracja", colCustomer: "Klient", colCompany: "Nazwa firmy", colOrderId: "Numer zamówienia", colPlacedAt: "Złożono", colPayment: "Metoda płatności", colFulfilment: "Czas realizacji", columns: "Kolumny", allRestaurants: "Wszystkie restauracje.", allTypes: "Wszystkie typy", notApplicable: "—", type_delivery: "Dostawa", type_pickup: "Odbiór osobisty", type_on_premise: "Na miejscu", type_catering: "Katering", type_table_reservation: "Rezerwacja stolika", type_reservation_preorder: "Rezerwacja i zamówienie z wyprzedzeniem", tabDetail: "Szczegóły zamówienia", tabItems: "Pozycje zamówienia", showLess: "Pokaż mniej", lblConfirmedAt: "Potwierdzono", lblFulfilledAt: "Zrealizowano", lblCredit: "Kredyt w lokalu", lblGuests: "Goście", lblDeposit: "Zadatek", lblPreOrder: "Zamówienie z wyprzedzeniem", lblCode: "Kod potwierdzenia", loadError: "Nie udało się wczytać tego zamówienia. Spróbuj ponownie.", export: "Eksportuj", showOlder: "Pokaż zamówienia starsze niż 30 dni", narrowRange: "Osiągnięto limit tego, co możemy pokazać naraz. Zawęź zakres dat lub filtruj według restauracji albo typu, aby zobaczyć więcej.", mixedCurrencyNote: "Twoje restauracje używają więcej niż jednej waluty, dlatego każda suma jest pokazywana w walucie swojej restauracji, a sumy nigdy nie są dodawane do siebie." },
  pt: { pageTitle: "Lista de encomendas", pageTitlePlatform: "Lista de encomendas — Todos os restaurantes", countLabel: "{count, plural, one {# resultado} other {# resultados}} · {range}", searchPlaceholder: "Pesquisar nome, ID da encomenda, telefone, e-mail…", colRestaurant: "Restaurante", colCustomer: "Cliente", colCompany: "Nome da empresa", colOrderId: "ID da encomenda", colPlacedAt: "Efetuada em", colPayment: "Método de pagamento", colFulfilment: "Hora de entrega", columns: "Colunas", allRestaurants: "Todos os restaurantes.", allTypes: "Todos os tipos", notApplicable: "N/D", type_delivery: "Entrega", type_pickup: "Recolha", type_on_premise: "No local", type_catering: "Catering", type_table_reservation: "Reserva de mesa", type_reservation_preorder: "Reserva e encomenda antecipada", tabDetail: "Detalhe da encomenda", tabItems: "Artigos da encomenda", showLess: "Mostrar menos", lblConfirmedAt: "Confirmada em", lblFulfilledAt: "Entregue em", lblCredit: "Crédito da loja", lblGuests: "Convidados", lblDeposit: "Sinal", lblPreOrder: "Encomenda antecipada", lblCode: "Código de confirmação", loadError: "Não foi possível carregar esta encomenda. Tente novamente.", export: "Exportar", showOlder: "Mostrar encomendas com mais de 30 dias", narrowRange: "Atingiu o limite do que podemos percorrer de uma vez. Reduza o intervalo de datas, ou filtre por restaurante ou tipo, para ver mais.", mixedCurrencyNote: "Os seus restaurantes usam mais do que uma moeda, por isso cada total é apresentado na moeda do respetivo restaurante e os totais nunca são somados." },
  "pt-BR": { pageTitle: "Lista de pedidos", pageTitlePlatform: "Lista de pedidos — Todos os restaurantes", countLabel: "{count, plural, one {# resultado} other {# resultados}} · {range}", searchPlaceholder: "Buscar nome, ID do pedido, telefone, e-mail…", colRestaurant: "Restaurante", colCustomer: "Cliente", colCompany: "Razão social", colOrderId: "ID do pedido", colPlacedAt: "Feito em", colPayment: "Forma de pagamento", colFulfilment: "Horário de entrega", columns: "Colunas", allRestaurants: "Todos os restaurantes.", allTypes: "Todos os tipos", notApplicable: "N/D", type_delivery: "Entrega", type_pickup: "Retirada", type_on_premise: "No local", type_catering: "Bufê", type_table_reservation: "Reserva de mesa", type_reservation_preorder: "Reserva e pedido antecipado", tabDetail: "Detalhes do pedido", tabItems: "Itens do pedido", showLess: "Mostrar menos", lblConfirmedAt: "Confirmado em", lblFulfilledAt: "Entregue em", lblCredit: "Crédito da loja", lblGuests: "Convidados", lblDeposit: "Sinal", lblPreOrder: "Pedido antecipado", lblCode: "Código de confirmação", loadError: "Não foi possível carregar este pedido. Tente novamente.", export: "Exportar", showOlder: "Mostrar pedidos com mais de 30 dias", narrowRange: "Você chegou ao limite do que podemos exibir de uma vez. Reduza o intervalo de datas, ou filtre por restaurante ou tipo, para ver mais.", mixedCurrencyNote: "Seus restaurantes usam mais de uma moeda, então cada total é mostrado na moeda do próprio restaurante e os totais nunca são somados." },
  ro: { pageTitle: "Lista comenzilor", pageTitlePlatform: "Lista comenzilor — Toate restaurantele", countLabel: "{count, plural, one {# rezultat} few {# rezultate} other {# de rezultate}} · {range}", searchPlaceholder: "Caută nume, ID comandă, telefon, e-mail…", colRestaurant: "Restaurant", colCustomer: "Client", colCompany: "Denumire firmă", colOrderId: "ID comandă", colPlacedAt: "Plasată la", colPayment: "Metodă de plată", colFulfilment: "Ora de onorare", columns: "Coloane", allRestaurants: "Toate restaurantele.", allTypes: "Toate tipurile", notApplicable: "—", type_delivery: "Livrare", type_pickup: "Ridicare", type_on_premise: "La local", type_catering: "Catering", type_table_reservation: "Rezervare masă", type_reservation_preorder: "Rezervare și precomandă", tabDetail: "Detalii comandă", tabItems: "Produse comandate", showLess: "Arată mai puțin", lblConfirmedAt: "Confirmată la", lblFulfilledAt: "Onorată la", lblCredit: "Credit în local", lblGuests: "Invitați", lblDeposit: "Avans", lblPreOrder: "Precomandă", lblCode: "Cod de confirmare", loadError: "Comanda nu a putut fi încărcată. Încearcă din nou.", export: "Exportă", showOlder: "Arată comenzile mai vechi de 30 de zile", narrowRange: "Ai ajuns la limita a ceea ce putem afișa deodată. Restrânge intervalul de date sau filtrează după restaurant ori tip pentru a vedea mai multe.", mixedCurrencyNote: "Restaurantele tale folosesc mai multe monede, așa că fiecare total este afișat în moneda propriului restaurant, iar totalurile nu se adună niciodată." },
  ru: { pageTitle: "Список заказов", pageTitlePlatform: "Список заказов — все рестораны", countLabel: "{count, plural, one {# результат} few {# результата} many {# результатов} other {# результата}} · {range}", searchPlaceholder: "Поиск по имени, номеру заказа, телефону, эл. почте…", colRestaurant: "Ресторан", colCustomer: "Клиент", colCompany: "Название компании", colOrderId: "Номер заказа", colPlacedAt: "Оформлен", colPayment: "Способ оплаты", colFulfilment: "Время выполнения", columns: "Столбцы", allRestaurants: "Все рестораны.", allTypes: "Все типы", notApplicable: "—", type_delivery: "Доставка", type_pickup: "Самовывоз", type_on_premise: "В заведении", type_catering: "Кейтеринг", type_table_reservation: "Бронирование столика", type_reservation_preorder: "Бронирование и предзаказ", tabDetail: "Детали заказа", tabItems: "Позиции заказа", showLess: "Показать меньше", lblConfirmedAt: "Подтверждён", lblFulfilledAt: "Выполнен", lblCredit: "Кредит заведения", lblGuests: "Гости", lblDeposit: "Депозит", lblPreOrder: "Предзаказ", lblCode: "Код подтверждения", loadError: "Не удалось загрузить этот заказ. Попробуйте ещё раз.", export: "Экспорт", showOlder: "Показать заказы старше 30 дней", narrowRange: "Вы достигли предела того, что можно пролистать за раз. Сузьте диапазон дат или отфильтруйте по ресторану либо типу, чтобы увидеть больше.", mixedCurrencyNote: "Ваши рестораны используют несколько валют, поэтому каждая сумма показана в валюте своего ресторана, и суммы никогда не складываются." },
  sk: { pageTitle: "Zoznam objednávok", pageTitlePlatform: "Zoznam objednávok — všetky reštaurácie", countLabel: "{count, plural, one {# výsledok} few {# výsledky} many {# výsledku} other {# výsledkov}} · {range}", searchPlaceholder: "Hľadať meno, číslo objednávky, telefón, e-mail…", colRestaurant: "Reštaurácia", colCustomer: "Zákazník", colCompany: "Názov firmy", colOrderId: "Číslo objednávky", colPlacedAt: "Vytvorené", colPayment: "Spôsob platby", colFulfilment: "Čas vybavenia", columns: "Stĺpce", allRestaurants: "Všetky reštaurácie.", allTypes: "Všetky typy", notApplicable: "—", type_delivery: "Rozvoz", type_pickup: "Vyzdvihnutie", type_on_premise: "Na mieste", type_catering: "Catering", type_table_reservation: "Rezervácia stola", type_reservation_preorder: "Rezervácia a predobjednávka", tabDetail: "Detail objednávky", tabItems: "Položky objednávky", showLess: "Zobraziť menej", lblConfirmedAt: "Potvrdené", lblFulfilledAt: "Vybavené", lblCredit: "Kredit v podniku", lblGuests: "Hostia", lblDeposit: "Záloha", lblPreOrder: "Predobjednávka", lblCode: "Potvrdzovací kód", loadError: "Objednávku sa nepodarilo načítať. Skúste to znova.", export: "Exportovať", showOlder: "Zobraziť objednávky staršie ako 30 dní", narrowRange: "Dosiahli ste maximum, ktoré vieme zobraziť naraz. Zúžte časové obdobie alebo filtrujte podľa reštaurácie či typu.", mixedCurrencyNote: "Vaše reštaurácie používajú viac mien, preto sa každý súčet zobrazuje v mene danej reštaurácie a súčty sa nikdy nespočítavajú." },
  sl: { pageTitle: "Seznam naročil", pageTitlePlatform: "Seznam naročil — vse restavracije", countLabel: "{count, plural, one {# zadetek} two {# zadetka} few {# zadetki} other {# zadetkov}} · {range}", searchPlaceholder: "Iskanje imena, ID naročila, telefona, e-pošte…", colRestaurant: "Restavracija", colCustomer: "Stranka", colCompany: "Naziv podjetja", colOrderId: "ID naročila", colPlacedAt: "Oddano", colPayment: "Način plačila", colFulfilment: "Čas izvedbe", columns: "Stolpci", allRestaurants: "Vse restavracije.", allTypes: "Vse vrste", notApplicable: "—", type_delivery: "Dostava", type_pickup: "Prevzem", type_on_premise: "V lokalu", type_catering: "Catering", type_table_reservation: "Rezervacija mize", type_reservation_preorder: "Rezervacija in prednaročilo", tabDetail: "Podrobnosti naročila", tabItems: "Postavke naročila", showLess: "Prikaži manj", lblConfirmedAt: "Potrjeno", lblFulfilledAt: "Izvedeno", lblCredit: "Dobroimetje", lblGuests: "Gostje", lblDeposit: "Polog", lblPreOrder: "Prednaročilo", lblCode: "Potrditvena koda", loadError: "Tega naročila ni bilo mogoče naložiti. Poskusite znova.", export: "Izvozi", showOlder: "Prikaži naročila, starejša od 30 dni", narrowRange: "Dosegli ste mejo tega, kar lahko prikažemo naenkrat. Zožite časovno obdobje ali filtrirajte po restavraciji ali vrsti.", mixedCurrencyNote: "Vaše restavracije uporabljajo več kot eno valuto, zato je vsak skupni znesek prikazan v valuti svoje restavracije in zneski se nikoli ne seštevajo." },
  // Serbian LATIN, ekavian — sr.json is ~85% Latin script (money.*, all of
  // marketing.signup, …); the first draft of this pack was Cyrillic, which made
  // an sr admin see a Latin signup page and a Cyrillic orders list. Fable
  // review 2026-08-09.
  sr: { pageTitle: "Spisak porudžbina", pageTitlePlatform: "Spisak porudžbina — svi restorani", countLabel: "{count, plural, one {# rezultat} few {# rezultata} other {# rezultata}} · {range}", searchPlaceholder: "Pretraži ime, broj porudžbine, telefon, imejl…", colRestaurant: "Restoran", colCustomer: "Kupac", colCompany: "Naziv firme", colOrderId: "Broj porudžbine", colPlacedAt: "Napravljena", colPayment: "Način plaćanja", colFulfilment: "Vreme izvršenja", columns: "Kolone", allRestaurants: "Svi restorani.", allTypes: "Svi tipovi", notApplicable: "—", type_delivery: "Dostava", type_pickup: "Preuzimanje", type_on_premise: "U lokalu", type_catering: "Ketering", type_table_reservation: "Rezervacija stola", type_reservation_preorder: "Rezervacija i porudžbina unapred", tabDetail: "Detalji porudžbine", tabItems: "Stavke porudžbine", showLess: "Prikaži manje", lblConfirmedAt: "Potvrđena", lblFulfilledAt: "Izvršena", lblCredit: "Kredit u lokalu", lblGuests: "Gosti", lblDeposit: "Depozit", lblPreOrder: "Porudžbina unapred", lblCode: "Kod potvrde", loadError: "Nije moguće učitati ovu porudžbinu. Pokušajte ponovo.", export: "Izvezi", showOlder: "Prikaži porudžbine starije od 30 dana", narrowRange: "Dostigli ste granicu onoga što možemo prikazati odjednom. Suzite raspon datuma ili filtrirajte po restoranu ili tipu.", mixedCurrencyNote: "Vaši restorani koriste više od jedne valute, pa se svaki iznos prikazuje u valuti svog restorana i iznosi se nikada ne sabiraju." },
  sv: { pageTitle: "Orderlista", pageTitlePlatform: "Orderlista — alla restauranger", countLabel: "{count, plural, one {# resultat} other {# resultat}} · {range}", searchPlaceholder: "Sök namn, order-ID, telefon, e-post…", colRestaurant: "Restaurang", colCustomer: "Kund", colCompany: "Företagsnamn", colOrderId: "Order-ID", colPlacedAt: "Lagd", colPayment: "Betalsätt", colFulfilment: "Leveranstid", columns: "Kolumner", allRestaurants: "Alla restauranger.", allTypes: "Alla typer", notApplicable: "—", type_delivery: "Leverans", type_pickup: "Avhämtning", type_on_premise: "På plats", type_catering: "Catering", type_table_reservation: "Bordsbokning", type_reservation_preorder: "Bokning och förbeställning", tabDetail: "Orderdetaljer", tabItems: "Orderrader", showLess: "Visa mindre", lblConfirmedAt: "Bekräftad", lblFulfilledAt: "Levererad", lblCredit: "Butikskredit", lblGuests: "Gäster", lblDeposit: "Handpenning", lblPreOrder: "Förbeställning", lblCode: "Bekräftelsekod", loadError: "Det gick inte att läsa in ordern. Försök igen.", export: "Exportera", showOlder: "Visa ordrar äldre än 30 dagar", narrowRange: "Du har nått så långt vi kan bläddra på en gång. Begränsa datumintervallet, eller filtrera på restaurang eller typ, för att se mer.", mixedCurrencyNote: "Dina restauranger använder mer än en valuta, så varje summa visas i sin egen restaurangs valuta och summor läggs aldrig ihop." },
  th: { pageTitle: "รายการคำสั่งซื้อ", pageTitlePlatform: "รายการคำสั่งซื้อ — ร้านทั้งหมด", countLabel: "{count, plural, other {# รายการ}} · {range}", searchPlaceholder: "ค้นหาชื่อ รหัสคำสั่งซื้อ โทรศัพท์ อีเมล…", colRestaurant: "ร้านอาหาร", colCustomer: "ลูกค้า", colCompany: "ชื่อบริษัท", colOrderId: "รหัสคำสั่งซื้อ", colPlacedAt: "สั่งเมื่อ", colPayment: "วิธีชำระเงิน", colFulfilment: "เวลาที่ดำเนินการ", columns: "คอลัมน์", allRestaurants: "ร้านทั้งหมด", allTypes: "ทุกประเภท", notApplicable: "ไม่มี", type_delivery: "จัดส่ง", type_pickup: "รับเอง", type_on_premise: "ทานที่ร้าน", type_catering: "จัดเลี้ยง", type_table_reservation: "จองโต๊ะ", type_reservation_preorder: "จองโต๊ะและสั่งล่วงหน้า", tabDetail: "รายละเอียดคำสั่งซื้อ", tabItems: "รายการสินค้า", showLess: "แสดงน้อยลง", lblConfirmedAt: "ยืนยันเมื่อ", lblFulfilledAt: "ดำเนินการเมื่อ", lblCredit: "เครดิตร้าน", lblGuests: "จำนวนแขก", lblDeposit: "เงินมัดจำ", lblPreOrder: "สั่งล่วงหน้า", lblCode: "รหัสยืนยัน", loadError: "ไม่สามารถโหลดคำสั่งซื้อนี้ได้ กรุณาลองใหม่อีกครั้ง", export: "ส่งออก", showOlder: "แสดงคำสั่งซื้อที่เก่ากว่า 30 วัน", narrowRange: "คุณดูครบเท่าที่เราแสดงได้ในครั้งเดียวแล้ว กรุณาลดช่วงวันที่ หรือกรองตามร้านหรือประเภท เพื่อดูเพิ่มเติม", mixedCurrencyNote: "ร้านของคุณใช้สกุลเงินมากกว่าหนึ่งสกุล ยอดรวมแต่ละรายการจึงแสดงในสกุลเงินของร้านนั้น ๆ และจะไม่ถูกนำมารวมกัน" },
  tr: { pageTitle: "Sipariş listesi", pageTitlePlatform: "Sipariş listesi — Tüm restoranlar", countLabel: "{count, plural, one {# sonuç} other {# sonuç}} · {range}", searchPlaceholder: "Ad, sipariş kimliği, telefon, e-posta ara…", colRestaurant: "Restoran", colCustomer: "Müşteri", colCompany: "Firma adı", colOrderId: "Sipariş kimliği", colPlacedAt: "Verilme zamanı", colPayment: "Ödeme yöntemi", colFulfilment: "Teslim zamanı", columns: "Sütunlar", allRestaurants: "Tüm restoranlar.", allTypes: "Tüm türler", notApplicable: "—", type_delivery: "Teslimat", type_pickup: "Gel al", type_on_premise: "Mekânda", type_catering: "Catering", type_table_reservation: "Masa rezervasyonu", type_reservation_preorder: "Rezervasyon ve ön sipariş", tabDetail: "Sipariş ayrıntısı", tabItems: "Sipariş kalemleri", showLess: "Daha az göster", lblConfirmedAt: "Onaylanma", lblFulfilledAt: "Tamamlanma", lblCredit: "Mağaza kredisi", lblGuests: "Misafirler", lblDeposit: "Kapora", lblPreOrder: "Ön sipariş", lblCode: "Onay kodu", loadError: "Bu sipariş yüklenemedi. Lütfen tekrar deneyin.", export: "Dışa aktar", showOlder: "30 günden eski siparişleri göster", narrowRange: "Tek seferde gösterebileceğimiz sınıra ulaştınız. Daha fazlası için tarih aralığını daraltın ya da restorana veya türe göre filtreleyin.", mixedCurrencyNote: "Restoranlarınız birden fazla para birimi kullanıyor; bu nedenle her toplam kendi restoranının para biriminde gösterilir ve toplamlar asla birbirine eklenmez." },
  uk: { pageTitle: "Список замовлень", pageTitlePlatform: "Список замовлень — усі ресторани", countLabel: "{count, plural, one {# результат} few {# результати} many {# результатів} other {# результату}} · {range}", searchPlaceholder: "Пошук за іменем, номером замовлення, телефоном, е-поштою…", colRestaurant: "Ресторан", colCustomer: "Клієнт", colCompany: "Назва компанії", colOrderId: "Номер замовлення", colPlacedAt: "Оформлено", colPayment: "Спосіб оплати", colFulfilment: "Час виконання", columns: "Стовпці", allRestaurants: "Усі ресторани.", allTypes: "Усі типи", notApplicable: "—", type_delivery: "Доставка", type_pickup: "Самовивіз", type_on_premise: "У закладі", type_catering: "Кейтеринг", type_table_reservation: "Бронювання столика", type_reservation_preorder: "Бронювання та попереднє замовлення", tabDetail: "Деталі замовлення", tabItems: "Позиції замовлення", showLess: "Показати менше", lblConfirmedAt: "Підтверджено", lblFulfilledAt: "Виконано", lblCredit: "Кредит закладу", lblGuests: "Гості", lblDeposit: "Завдаток", lblPreOrder: "Попереднє замовлення", lblCode: "Код підтвердження", loadError: "Не вдалося завантажити це замовлення. Спробуйте ще раз.", export: "Експорт", showOlder: "Показати замовлення, старші за 30 днів", narrowRange: "Ви досягли межі того, що можна гортати за раз. Звузьте діапазон дат або відфільтруйте за рестораном чи типом, щоб побачити більше.", mixedCurrencyNote: "Ваші ресторани використовують кілька валют, тому кожна сума показана у валюті свого ресторану, і суми ніколи не додаються." },
  vi: { pageTitle: "Danh sách đơn hàng", pageTitlePlatform: "Danh sách đơn hàng — Tất cả nhà hàng", countLabel: "{count, plural, other {# kết quả}} · {range}", searchPlaceholder: "Tìm tên, mã đơn hàng, điện thoại, email…", colRestaurant: "Nhà hàng", colCustomer: "Khách hàng", colCompany: "Tên công ty", colOrderId: "Mã đơn hàng", colPlacedAt: "Đặt lúc", colPayment: "Phương thức thanh toán", colFulfilment: "Thời gian hoàn tất", columns: "Cột", allRestaurants: "Tất cả nhà hàng.", allTypes: "Tất cả loại", notApplicable: "—", type_delivery: "Giao hàng", type_pickup: "Tự đến lấy", type_on_premise: "Tại chỗ", type_catering: "Tiệc", type_table_reservation: "Đặt bàn", type_reservation_preorder: "Đặt bàn và đặt món trước", tabDetail: "Chi tiết đơn hàng", tabItems: "Món trong đơn", showLess: "Thu gọn", lblConfirmedAt: "Xác nhận lúc", lblFulfilledAt: "Hoàn tất lúc", lblCredit: "Tín dụng cửa hàng", lblGuests: "Số khách", lblDeposit: "Tiền đặt cọc", lblPreOrder: "Đặt trước", lblCode: "Mã xác nhận", loadError: "Không thể tải đơn hàng này. Vui lòng thử lại.", export: "Xuất dữ liệu", showOlder: "Hiện đơn hàng cũ hơn 30 ngày", narrowRange: "Bạn đã xem hết mức chúng tôi có thể hiển thị một lần. Hãy thu hẹp khoảng thời gian, hoặc lọc theo nhà hàng hay loại, để xem thêm.", mixedCurrencyNote: "Các nhà hàng của bạn dùng nhiều loại tiền tệ, nên mỗi tổng được hiển thị theo tiền tệ của nhà hàng đó và các tổng không bao giờ được cộng lại." },
  zh: { pageTitle: "订单列表", pageTitlePlatform: "订单列表 — 所有餐厅", countLabel: "{count, plural, other {# 条结果}} · {range}", searchPlaceholder: "搜索姓名、订单编号、电话、邮箱…", colRestaurant: "餐厅", colCustomer: "顾客", colCompany: "公司名称", colOrderId: "订单编号", colPlacedAt: "下单时间", colPayment: "支付方式", colFulfilment: "完成时间", columns: "列", allRestaurants: "所有餐厅。", allTypes: "所有类型", notApplicable: "不适用", type_delivery: "配送", type_pickup: "自取", type_on_premise: "堂食", type_catering: "餐饮服务", type_table_reservation: "餐位预订", type_reservation_preorder: "预订并预点餐", tabDetail: "订单详情", tabItems: "订单商品", showLess: "收起", lblConfirmedAt: "确认时间", lblFulfilledAt: "完成时间", lblCredit: "店内余额", lblGuests: "人数", lblDeposit: "订金", lblPreOrder: "预点餐", lblCode: "确认码", loadError: "无法加载此订单，请重试。", export: "导出", showOlder: "显示 30 天前的订单", narrowRange: "已达到单次可翻阅的上限。请缩小日期范围，或按餐厅或类型筛选，以查看更多。", mixedCurrencyNote: "您的餐厅使用多种货币，因此每个金额都以其所属餐厅的货币显示，金额之间不会相加。" },
};

function get(obj: any, pathParts: string[]) {
  return pathParts.reduce((o, k) => (o == null ? o : o[k]), obj);
}

function main() {
  const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".json"));
  const locales = files.map((f) => f.replace(/\.json$/, ""));
  const enSrc = get(JSON.parse(fs.readFileSync(path.join(DIR, "en.json"), "utf8")), NS) as Pack;
  const KEYS = Object.keys(enSrc);

  const problems: string[] = [];
  for (const loc of locales) {
    if (loc === "en") continue;
    const pack = PACKS[loc];
    if (!pack) { problems.push(`missing pack for "${loc}"`); continue; }
    for (const k of KEYS) {
      const v = pack[k];
      if (v === undefined || !String(v).trim()) { problems.push(`${loc}.${k} missing/empty`); continue; }
      // every {placeholder} in English must survive
      const args = [...String(enSrc[k]).matchAll(/\{(\w+)[,}]/g)].map((m) => m[1]);
      for (const a of args) {
        if (!new RegExp(`\\{${a}[,}]`).test(v)) problems.push(`${loc}.${k} lost {${a}}`);
      }
      if (String(enSrc[k]).includes("plural") && !v.includes("other {")) {
        problems.push(`${loc}.${k} plural has no "other" branch`);
      }
    }
    for (const k of Object.keys(pack)) {
      if (!KEYS.includes(k)) problems.push(`${loc}.${k} is not a key in en.json`);
    }
  }
  if (problems.length) {
    console.error("❌ ABORTED — nothing written:");
    for (const p of problems) console.error("   " + p);
    process.exit(1);
  }

  let n = 0;
  for (const loc of locales) {
    if (loc === "en") continue;
    const file = path.join(DIR, `${loc}.json`);
    const json = JSON.parse(fs.readFileSync(file, "utf8"));
    const target = get(json, NS);
    for (const k of KEYS) target[k] = PACKS[loc][k];
    if (WRITE) fs.writeFileSync(file, JSON.stringify(json, null, 2) + "\n", "utf8");
    n++;
  }
  console.log(`${WRITE ? "✅ wrote" : "🔍 dry run —"} ${KEYS.length} keys × ${n} locales (en untouched)`);
  if (!WRITE) console.log("   re-run with --write to apply");
}

main();
