/**
 * A1b (2026-08-22) — MERGE (never replace) the Nabil "Transfers" settings keys
 * into `admin.phoneOrderingPage.config` and the `message_taken` outcome label
 * into `admin.phoneOrderingPage.callLog.outcome`, fully translated ×38.
 *
 *   npx tsx scripts/i18n-add-nabil-transfer-policy.ts
 *
 * Fails loudly if a locale file has no translation block (parity is part of
 * "done"). Re-runnable: identical values are idempotent.
 */
import fs from "node:fs";
import path from "node:path";

const DIR = path.join(process.cwd(), "src", "messages");
const CONFIG_KEYS = [
  "transferPolicy",
  "tpImmediate",
  "tpReluctant",
  "tpNever",
  "transferPolicyHint",
  "transferDeflection",
  "transferDeflectionHint",
  "transferTakeMessage",
  "transferTakeMessageHint",
] as const;

// [9 config strings..., outcome label]
const T: Record<string, string[]> = {
  en: ["When a caller asks for a person", "Transfer right away", "Only if they insist (asks twice)", "Never transfer — Nabil handles it and takes messages", "Nabil enforces this on every call. With “Only if they insist” and “Never”, it says the line below instead and keeps helping. If the AI itself breaks down, the call still rings your phone so nobody is left hanging.", "What Nabil says instead of transferring", "Spoken word for word. Leave empty for: “Our staff are busy preparing orders and can't take calls right now, but I can help with anything about the restaurant.”", "Offer to take a message", "When a caller can't be put through, Nabil offers to take a message and texts it to your transfer number (or alert phone).", "Message taken"],
  fr: ["Quand un client demande une personne", "Transférer tout de suite", "Seulement s'il insiste (demande deux fois)", "Ne jamais transférer — Nabil s'en occupe et prend les messages", "Nabil applique ce réglage à chaque appel. Avec « Seulement s'il insiste » et « Ne jamais », il dit la phrase ci-dessous à la place et continue d'aider. Si l'IA elle-même tombe en panne, l'appel sonne quand même sur votre téléphone pour que personne ne reste sans réponse.", "Ce que Nabil dit au lieu de transférer", "Dit mot pour mot. Laissez vide pour : « Notre équipe est occupée à préparer les commandes et ne peut pas prendre d'appels pour le moment, mais je peux vous aider pour tout ce qui concerne le restaurant. »", "Proposer de prendre un message", "Quand un client ne peut pas être transféré, Nabil propose de prendre un message et l'envoie par SMS à votre numéro de transfert (ou au téléphone d'alerte).", "Message pris"],
  es: ["Cuando quien llama pide hablar con una persona", "Transferir de inmediato", "Solo si insiste (lo pide dos veces)", "Nunca transferir — Nabil se encarga y toma mensajes", "Nabil aplica esto en cada llamada. Con «Solo si insiste» y «Nunca», dice la frase de abajo en su lugar y sigue ayudando. Si la propia IA falla, la llamada sigue sonando en su teléfono para que nadie quede sin atender.", "Lo que Nabil dice en lugar de transferir", "Se dice palabra por palabra. Déjelo vacío para: «Nuestro personal está ocupado preparando pedidos y no puede atender llamadas ahora mismo, pero puedo ayudarle con cualquier cosa sobre el restaurante.»", "Ofrecer tomar un mensaje", "Cuando no se puede pasar la llamada, Nabil ofrece tomar un mensaje y lo envía por SMS a su número de transferencia (o al teléfono de alertas).", "Mensaje tomado"],
  it: ["Quando chi chiama chiede di parlare con una persona", "Trasferisci subito", "Solo se insiste (lo chiede due volte)", "Mai trasferire — Nabil se ne occupa e prende i messaggi", "Nabil lo applica a ogni chiamata. Con «Solo se insiste» e «Mai», dice invece la frase qui sotto e continua ad aiutare. Se è l'IA stessa a bloccarsi, la chiamata squilla comunque sul suo telefono, così nessuno resta senza risposta.", "Cosa dice Nabil invece di trasferire", "Detto parola per parola. Lasci vuoto per: «Il nostro staff è impegnato a preparare gli ordini e al momento non può rispondere alle chiamate, ma posso aiutarla con qualsiasi cosa riguardi il ristorante.»", "Offrire di prendere un messaggio", "Quando non è possibile passare la chiamata, Nabil offre di prendere un messaggio e lo invia via SMS al suo numero di trasferimento (o al telefono degli avvisi).", "Messaggio preso"],
  pt: ["Quando quem liga pede para falar com uma pessoa", "Transferir de imediato", "Só se insistir (pede duas vezes)", "Nunca transferir — o Nabil trata de tudo e anota mensagens", "O Nabil aplica isto em todas as chamadas. Com «Só se insistir» e «Nunca», diz a frase abaixo em vez disso e continua a ajudar. Se a própria IA falhar, a chamada continua a tocar no seu telefone para que ninguém fique sem resposta.", "O que o Nabil diz em vez de transferir", "Dito palavra por palavra. Deixe vazio para: «A nossa equipa está ocupada a preparar pedidos e não pode atender chamadas neste momento, mas posso ajudar com qualquer assunto sobre o restaurante.»", "Oferecer anotar uma mensagem", "Quando não é possível passar a chamada, o Nabil oferece-se para anotar uma mensagem e envia-a por SMS para o seu número de transferência (ou telefone de alertas).", "Mensagem anotada"],
  "pt-BR": ["Quando quem liga pede para falar com uma pessoa", "Transferir na hora", "Só se insistir (pede duas vezes)", "Nunca transferir — o Nabil resolve e anota recados", "O Nabil aplica isso em todas as ligações. Com “Só se insistir” e “Nunca”, ele diz a frase abaixo no lugar e continua ajudando. Se a própria IA travar, a ligação ainda toca no seu telefone para ninguém ficar sem resposta.", "O que o Nabil diz em vez de transferir", "Dito palavra por palavra. Deixe em branco para: “Nossa equipe está ocupada preparando pedidos e não pode atender ligações agora, mas posso ajudar com qualquer coisa sobre o restaurante.”", "Oferecer anotar um recado", "Quando não dá para passar a ligação, o Nabil se oferece para anotar um recado e envia por SMS para o seu número de transferência (ou telefone de alertas).", "Recado anotado"],
  de: ["Wenn ein Anrufer eine Person verlangt", "Sofort weiterleiten", "Nur wenn er darauf besteht (zweimal fragt)", "Nie weiterleiten — Nabil erledigt es und nimmt Nachrichten auf", "Nabil setzt das bei jedem Anruf durch. Bei „Nur wenn er darauf besteht“ und „Nie“ sagt Nabil stattdessen den Satz unten und hilft weiter. Fällt die KI selbst aus, klingelt der Anruf trotzdem auf Ihrem Telefon, damit niemand hängen bleibt.", "Was Nabil statt einer Weiterleitung sagt", "Wird wörtlich gesprochen. Leer lassen für: „Unser Team ist gerade mit der Zubereitung von Bestellungen beschäftigt und kann im Moment keine Anrufe annehmen, aber ich helfe gern bei allem rund um das Restaurant.“", "Anbieten, eine Nachricht aufzunehmen", "Wenn ein Anrufer nicht durchgestellt werden kann, bietet Nabil an, eine Nachricht aufzunehmen, und schickt sie per SMS an Ihre Weiterleitungsnummer (oder das Alarm-Telefon).", "Nachricht aufgenommen"],
  nl: ["Wanneer een beller om een persoon vraagt", "Meteen doorverbinden", "Alleen als de beller aandringt (twee keer vraagt)", "Nooit doorverbinden — Nabil handelt het af en neemt berichten aan", "Nabil past dit bij elk gesprek toe. Bij „Alleen als de beller aandringt” en „Nooit” zegt Nabil in plaats daarvan de zin hieronder en blijft helpen. Als de AI zelf uitvalt, gaat de oproep alsnog over op uw telefoon, zodat niemand in de wacht blijft hangen.", "Wat Nabil zegt in plaats van doorverbinden", "Wordt woordelijk uitgesproken. Laat leeg voor: „Ons team is druk met het bereiden van bestellingen en kan op dit moment geen telefoontjes aannemen, maar ik kan u helpen met alles over het restaurant.”", "Aanbieden een bericht aan te nemen", "Als een beller niet kan worden doorverbonden, biedt Nabil aan een bericht aan te nemen en stuurt dit per sms naar uw doorverbindnummer (of alarmtelefoon).", "Bericht aangenomen"],
  ro: ["Când apelantul cere să vorbească cu o persoană", "Transferă imediat", "Doar dacă insistă (cere de două ori)", "Nu transfera niciodată — Nabil se ocupă și preia mesaje", "Nabil aplică această regulă la fiecare apel. Cu „Doar dacă insistă” și „Niciodată”, spune în schimb fraza de mai jos și continuă să ajute. Dacă IA însăși se blochează, apelul tot sună pe telefonul dvs., ca nimeni să nu rămână fără răspuns.", "Ce spune Nabil în loc să transfere", "Rostit cuvânt cu cuvânt. Lăsați gol pentru: „Personalul nostru este ocupat cu pregătirea comenzilor și nu poate prelua apeluri acum, dar vă pot ajuta cu orice legat de restaurant.”", "Oferă preluarea unui mesaj", "Când apelantul nu poate fi transferat, Nabil se oferă să preia un mesaj și îl trimite prin SMS la numărul de transfer (sau la telefonul de alertă).", "Mesaj preluat"],
  sv: ["När den som ringer ber om en person", "Koppla vidare direkt", "Bara om personen insisterar (frågar två gånger)", "Koppla aldrig vidare — Nabil sköter det och tar meddelanden", "Nabil tillämpar detta vid varje samtal. Med ”Bara om personen insisterar” och ”Aldrig” säger Nabil i stället raden nedan och fortsätter hjälpa till. Om själva AI:n slutar fungera ringer samtalet ändå din telefon så att ingen blir hängande.", "Vad Nabil säger i stället för att koppla vidare", "Sägs ord för ord. Lämna tomt för: ”Vår personal är upptagen med att förbereda beställningar och kan inte ta samtal just nu, men jag kan hjälpa till med allt som rör restaurangen.”", "Erbjud att ta ett meddelande", "När ett samtal inte kan kopplas vidare erbjuder Nabil att ta ett meddelande och skickar det som sms till ditt vidarekopplingsnummer (eller larmtelefonen).", "Meddelande mottaget"],
  da: ["Når en opkalder beder om en person", "Stil om med det samme", "Kun hvis opkalderen insisterer (spørger to gange)", "Stil aldrig om — Nabil klarer det og tager imod beskeder", "Nabil håndhæver dette ved hvert opkald. Med ”Kun hvis opkalderen insisterer” og ”Aldrig” siger Nabil i stedet linjen nedenfor og fortsætter med at hjælpe. Hvis selve AI'en går ned, ringer opkaldet stadig på din telefon, så ingen efterlades uden svar.", "Hvad Nabil siger i stedet for at stille om", "Siges ord for ord. Lad feltet stå tomt for: ”Vores personale har travlt med at tilberede ordrer og kan ikke tage imod opkald lige nu, men jeg kan hjælpe med alt om restauranten.”", "Tilbyd at tage imod en besked", "Når et opkald ikke kan stilles om, tilbyder Nabil at tage imod en besked og sender den som sms til dit omstillingsnummer (eller alarmtelefonen).", "Besked modtaget"],
  nb: ["Når en innringer ber om en person", "Sett over med en gang", "Bare hvis innringeren insisterer (spør to ganger)", "Sett aldri over — Nabil håndterer det og tar imot beskjeder", "Nabil håndhever dette på hver samtale. Med «Bare hvis innringeren insisterer» og «Aldri» sier Nabil linjen nedenfor i stedet og fortsetter å hjelpe. Hvis selve AI-en svikter, ringer samtalen fortsatt telefonen din, så ingen blir hengende.", "Hva Nabil sier i stedet for å sette over", "Sies ord for ord. La stå tomt for: «Personalet vårt er opptatt med å forberede bestillinger og kan ikke ta telefonen akkurat nå, men jeg kan hjelpe med alt som gjelder restauranten.»", "Tilby å ta imot en beskjed", "Når en innringer ikke kan settes over, tilbyr Nabil å ta imot en beskjed og sender den på SMS til overføringsnummeret ditt (eller varslingstelefonen).", "Beskjed mottatt"],
  fi: ["Kun soittaja pyytää puhua ihmisen kanssa", "Yhdistä heti", "Vain jos soittaja vaatii (pyytää kahdesti)", "Älä koskaan yhdistä — Nabil hoitaa asian ja ottaa viestit vastaan", "Nabil noudattaa tätä jokaisessa puhelussa. Vaihtoehdoilla ”Vain jos soittaja vaatii” ja ”Ei koskaan” Nabil sanoo sen sijaan alla olevan lauseen ja jatkaa auttamista. Jos tekoäly itse lakkaa toimimasta, puhelu soi silti puhelimeesi, jotta kukaan ei jää vaille vastausta.", "Mitä Nabil sanoo yhdistämisen sijaan", "Sanotaan sanasta sanaan. Jätä tyhjäksi, jolloin käytetään: ”Henkilökuntamme valmistaa parhaillaan tilauksia eikä voi vastata puheluihin juuri nyt, mutta voin auttaa kaikessa ravintolaan liittyvässä.”", "Tarjoa viestin jättämistä", "Kun soittajaa ei voi yhdistää, Nabil tarjoutuu ottamaan viestin ja lähettää sen tekstiviestinä siirtonumeroosi (tai hälytyspuhelimeen).", "Viesti otettu vastaan"],
  pl: ["Gdy dzwoniący prosi o rozmowę z osobą", "Przełącz od razu", "Tylko jeśli nalega (prosi dwa razy)", "Nigdy nie przełączaj — Nabil zajmie się tym i przyjmie wiadomość", "Nabil stosuje to przy każdej rozmowie. Przy „Tylko jeśli nalega” i „Nigdy” zamiast tego wypowiada poniższe zdanie i dalej pomaga. Jeśli sama sztuczna inteligencja zawiedzie, połączenie i tak zadzwoni na Twój telefon, by nikt nie został bez odpowiedzi.", "Co Nabil mówi zamiast przełączać", "Wypowiadane słowo w słowo. Zostaw puste, aby użyć: „Nasz personel jest zajęty przygotowywaniem zamówień i nie może teraz odbierać telefonów, ale mogę pomóc we wszystkim, co dotyczy restauracji.”", "Zaproponuj przyjęcie wiadomości", "Gdy nie można przełączyć rozmowy, Nabil proponuje przyjęcie wiadomości i wysyła ją SMS-em na Twój numer do przełączania (lub telefon alarmowy).", "Wiadomość przyjęta"],
  cs: ["Když volající žádá o spojení s člověkem", "Přepojit ihned", "Jen pokud trvá na svém (požádá dvakrát)", "Nikdy nepřepojovat — Nabil to vyřídí a přijme vzkaz", "Nabil to uplatňuje při každém hovoru. U možností „Jen pokud trvá na svém“ a „Nikdy“ místo toho řekne větu níže a dál pomáhá. Pokud selže samotná AI, hovor stále zazvoní na vašem telefonu, aby nikdo nezůstal bez odpovědi.", "Co Nabil řekne místo přepojení", "Říká se slovo od slova. Nechte prázdné pro: „Náš personál právě připravuje objednávky a nemůže teď přijímat hovory, ale mohu vám pomoci s čímkoli ohledně restaurace.“", "Nabídnout převzetí vzkazu", "Když volajícího nelze přepojit, Nabil nabídne převzetí vzkazu a pošle ho SMS na vaše číslo pro přepojení (nebo na telefon pro upozornění).", "Vzkaz přijat"],
  sk: ["Keď volajúci žiada o spojenie s človekom", "Prepojiť hneď", "Len ak trvá na svojom (požiada dvakrát)", "Nikdy neprepájať — Nabil to vybaví a prevezme odkaz", "Nabil to uplatňuje pri každom hovore. Pri možnostiach „Len ak trvá na svojom“ a „Nikdy“ namiesto toho povie vetu nižšie a ďalej pomáha. Ak zlyhá samotná AI, hovor stále zazvoní na vašom telefóne, aby nikto nezostal bez odpovede.", "Čo Nabil povie namiesto prepojenia", "Hovorí sa slovo za slovom. Nechajte prázdne pre: „Náš personál práve pripravuje objednávky a momentálne nemôže prijímať hovory, ale môžem vám pomôcť s čímkoľvek ohľadom reštaurácie.“", "Ponúknuť prevzatie odkazu", "Keď volajúceho nemožno prepojiť, Nabil ponúkne prevzatie odkazu a pošle ho SMS na vaše číslo na prepojenie (alebo na telefón pre upozornenia).", "Odkaz prevzatý"],
  hu: ["Amikor a hívó egy személyt kér", "Azonnali átkapcsolás", "Csak ha ragaszkodik hozzá (kétszer kéri)", "Soha ne kapcsolja át — Nabil intézi, és üzenetet vesz fel", "Nabil ezt minden hívásnál betartja. A „Csak ha ragaszkodik hozzá” és a „Soha” beállításnál ehelyett az alábbi mondatot mondja, és tovább segít. Ha maga az MI hibásodik meg, a hívás továbbra is kicseng az Ön telefonján, hogy senki ne maradjon válasz nélkül.", "Mit mond Nabil átkapcsolás helyett", "Szó szerint hangzik el. Hagyja üresen ehhez: „A személyzet éppen a rendeléseket készíti, és most nem tud hívást fogadni, de bármiben segítek, ami az étteremmel kapcsolatos.”", "Üzenet felvételének felajánlása", "Ha a hívót nem lehet átkapcsolni, Nabil felajánlja, hogy üzenetet vesz fel, és SMS-ben elküldi az átkapcsolási számára (vagy a riasztási telefonra).", "Üzenet felvéve"],
  el: ["Όταν ο καλών ζητά να μιλήσει με άνθρωπο", "Μεταφορά αμέσως", "Μόνο αν επιμείνει (ζητήσει δύο φορές)", "Ποτέ μεταφορά — ο Nabil το χειρίζεται και κρατά μηνύματα", "Ο Nabil το εφαρμόζει σε κάθε κλήση. Με «Μόνο αν επιμείνει» και «Ποτέ», λέει αντ' αυτού την παρακάτω φράση και συνεχίζει να βοηθά. Αν χαλάσει η ίδια η ΤΝ, η κλήση χτυπά κανονικά στο τηλέφωνό σας ώστε κανείς να μη μείνει χωρίς απάντηση.", "Τι λέει ο Nabil αντί για μεταφορά", "Λέγεται λέξη προς λέξη. Αφήστε κενό για: «Το προσωπικό μας ετοιμάζει παραγγελίες και δεν μπορεί να απαντήσει σε κλήσεις αυτή τη στιγμή, αλλά μπορώ να βοηθήσω με οτιδήποτε αφορά το εστιατόριο.»", "Προσφορά λήψης μηνύματος", "Όταν δεν είναι δυνατή η μεταφορά, ο Nabil προσφέρεται να κρατήσει μήνυμα και το στέλνει με SMS στον αριθμό μεταφοράς σας (ή στο τηλέφωνο ειδοποιήσεων).", "Μήνυμα καταγράφηκε"],
  bg: ["Когато обаждащият се поиска човек", "Прехвърляне веднага", "Само ако настоява (поиска два пъти)", "Никога не прехвърляй — Набил се справя и приема съобщения", "Набил прилага това при всяко обаждане. При „Само ако настоява“ и „Никога“ вместо това казва фразата по-долу и продължава да помага. Ако самият ИИ спре да работи, обаждането пак звъни на вашия телефон, за да не остане никой без отговор.", "Какво казва Набил вместо да прехвърли", "Казва се дума по дума. Оставете празно за: „Персоналът ни е зает с приготвянето на поръчки и в момента не може да приема обаждания, но мога да помогна с всичко, свързано с ресторанта.“", "Предложи да приеме съобщение", "Когато обаждащият се не може да бъде прехвърлен, Набил предлага да приеме съобщение и го изпраща с SMS на номера ви за прехвърляне (или на телефона за известия).", "Прието съобщение"],
  hr: ["Kada pozivatelj traži razgovor s osobom", "Odmah prespoji", "Samo ako inzistira (pita dvaput)", "Nikad ne prespajaj — Nabil rješava i prima poruke", "Nabil to primjenjuje na svaki poziv. Uz „Samo ako inzistira” i „Nikad” umjesto toga izgovara rečenicu u nastavku i nastavlja pomagati. Ako sama umjetna inteligencija zakaže, poziv i dalje zvoni na vašem telefonu da nitko ne ostane bez odgovora.", "Što Nabil kaže umjesto prespajanja", "Izgovara se od riječi do riječi. Ostavite prazno za: „Naše osoblje trenutno priprema narudžbe i ne može preuzimati pozive, ali mogu pomoći sa svime što se tiče restorana.”", "Ponudi primanje poruke", "Kada pozivatelja nije moguće prespojiti, Nabil nudi primanje poruke i šalje je SMS-om na vaš broj za prespajanje (ili telefon za obavijesti).", "Poruka primljena"],
  sr: ["Kada pozivalac traži razgovor sa osobom", "Odmah prebaci", "Samo ako insistira (pita dvaput)", "Nikad ne prebacuj — Nabil rešava i prima poruke", "Nabil ovo primenjuje na svaki poziv. Uz „Samo ako insistira” i „Nikad” umesto toga izgovara rečenicu ispod i nastavlja da pomaže. Ako sama veštačka inteligencija zakaže, poziv i dalje zvoni na vašem telefonu da niko ne ostane bez odgovora.", "Šta Nabil kaže umesto prebacivanja", "Izgovara se od reči do reči. Ostavite prazno za: „Naše osoblje trenutno priprema porudžbine i ne može da preuzima pozive, ali mogu da pomognem sa svime u vezi sa restoranom.”", "Ponudi primanje poruke", "Kada pozivaoca nije moguće prebaciti, Nabil nudi da primi poruku i šalje je SMS-om na vaš broj za prebacivanje (ili telefon za obaveštenja).", "Poruka primljena"],
  sl: ["Ko klicatelj zahteva pogovor z osebo", "Takoj preveži", "Samo če vztraja (vpraša dvakrat)", "Nikoli ne preveži — Nabil uredi in sprejme sporočila", "Nabil to uveljavlja pri vsakem klicu. Pri možnostih »Samo če vztraja« in »Nikoli« namesto tega pove spodnji stavek in še naprej pomaga. Če odpove sama umetna inteligenca, klic še vedno zvoni na vašem telefonu, da nihče ne ostane brez odgovora.", "Kaj Nabil reče namesto prevezave", "Izgovori dobesedno. Pustite prazno za: »Naše osebje trenutno pripravlja naročila in ne more sprejemati klicev, lahko pa vam pomagam z vsem v zvezi z restavracijo.«", "Ponudi sprejem sporočila", "Ko klicatelja ni mogoče prevezati, Nabil ponudi sprejem sporočila in ga pošlje prek SMS-a na vašo številko za prevezavo (ali telefon za opozorila).", "Sporočilo sprejeto"],
  et: ["Kui helistaja küsib inimest", "Suuna kohe edasi", "Ainult kui ta nõuab (küsib kaks korda)", "Ära kunagi suuna edasi — Nabil tegeleb ise ja võtab sõnumeid vastu", "Nabil rakendab seda igal kõnel. Valikutega „Ainult kui ta nõuab“ ja „Mitte kunagi“ ütleb ta selle asemel alloleva lause ja aitab edasi. Kui tehisintellekt ise tõrgub, heliseb kõne ikkagi teie telefonil, et keegi ei jääks vastuseta.", "Mida Nabil ütleb edasisuunamise asemel", "Öeldakse sõna-sõnalt. Jätke tühjaks, et kasutada: „Meie personal valmistab praegu tellimusi ega saa hetkel kõnesid vastu võtta, kuid saan aidata kõiges, mis puudutab restorani.“", "Paku sõnumi vastuvõtmist", "Kui helistajat ei saa edasi suunata, pakub Nabil sõnumi vastuvõtmist ja saadab selle SMS-iga teie edasisuunamise numbrile (või hoiatustelefonile).", "Sõnum vastu võetud"],
  lv: ["Kad zvanītājs lūdz runāt ar cilvēku", "Pārsavienot uzreiz", "Tikai ja uzstāj (lūdz divreiz)", "Nekad nepārsavienot — Nabil tiek galā un pieņem ziņas", "Nabil to piemēro katrā zvanā. Ar „Tikai ja uzstāj“ un „Nekad“ tā vietā tiek pateikts zemāk norādītais teikums un palīdzība turpinās. Ja pats MI pārstāj darboties, zvans tik un tā zvana uz jūsu tālruni, lai neviens nepaliktu bez atbildes.", "Ko Nabil saka pārsavienošanas vietā", "Tiek pateikts vārds vārdā. Atstājiet tukšu, lai izmantotu: „Mūsu personāls pašlaik gatavo pasūtījumus un nevar atbildēt uz zvaniem, bet es varu palīdzēt ar visu, kas saistīts ar restorānu.“", "Piedāvāt pieņemt ziņu", "Kad zvanītāju nevar pārsavienot, Nabil piedāvā pieņemt ziņu un nosūta to SMS veidā uz jūsu pārsavienošanas numuru (vai brīdinājumu tālruni).", "Ziņa pieņemta"],
  lt: ["Kai skambinantysis prašo pakalbėti su žmogumi", "Perjungti iš karto", "Tik jei primygtinai prašo (paprašo du kartus)", "Niekada neperjungti — Nabil susitvarko ir priima žinutes", "Nabil tai taiko kiekvienam skambučiui. Pasirinkus „Tik jei primygtinai prašo“ ir „Niekada“, vietoj to pasakomas žemiau esantis sakinys ir toliau padedama. Jei sutrinka pats DI, skambutis vis tiek skamba jūsų telefone, kad niekas neliktų be atsakymo.", "Ką Nabil sako vietoj perjungimo", "Sakoma žodis į žodį. Palikite tuščią, kad būtų naudojama: „Mūsų personalas šiuo metu ruošia užsakymus ir negali atsiliepti į skambučius, bet galiu padėti viskuo, kas susiję su restoranu.“", "Pasiūlyti priimti žinutę", "Kai skambinančiojo negalima perjungti, Nabil pasiūlo priimti žinutę ir išsiunčia ją SMS žinute jūsų perjungimo numeriu (arba įspėjimų telefonu).", "Žinutė priimta"],
  tr: ["Arayan bir kişiyle görüşmek istediğinde", "Hemen aktar", "Sadece ısrar ederse (iki kez isterse)", "Asla aktarma — Nabil halleder ve mesaj alır", "Nabil bunu her aramada uygular. “Sadece ısrar ederse” ve “Asla” seçeneklerinde bunun yerine aşağıdaki cümleyi söyler ve yardım etmeye devam eder. Yapay zekânın kendisi arızalanırsa arama yine de telefonunuzu çalar, böylece kimse yanıtsız kalmaz.", "Nabil aktarmak yerine ne söyler", "Kelimesi kelimesine söylenir. Şunun için boş bırakın: “Ekibimiz şu anda siparişleri hazırlamakla meşgul ve telefonlara bakamıyor, ama restoranla ilgili her konuda yardımcı olabilirim.”", "Mesaj almayı teklif et", "Arayan aktarılamadığında Nabil mesaj almayı teklif eder ve bunu aktarma numaranıza (veya uyarı telefonuna) SMS ile gönderir.", "Mesaj alındı"],
  ru: ["Когда звонящий просит соединить с человеком", "Переводить сразу", "Только если настаивает (просит дважды)", "Никогда не переводить — Набил справляется сам и принимает сообщения", "Набил применяет это к каждому звонку. При «Только если настаивает» и «Никогда» он вместо этого произносит фразу ниже и продолжает помогать. Если сбой произойдёт у самого ИИ, звонок всё равно поступит на ваш телефон, чтобы никто не остался без ответа.", "Что Набил говорит вместо перевода", "Произносится слово в слово. Оставьте пустым, чтобы использовать: «Наши сотрудники сейчас заняты приготовлением заказов и не могут ответить на звонок, но я могу помочь со всем, что касается ресторана.»", "Предлагать принять сообщение", "Если перевести звонок нельзя, Набил предлагает принять сообщение и отправляет его по SMS на ваш номер для перевода (или телефон для оповещений).", "Сообщение принято"],
  uk: ["Коли той, хто телефонує, просить з'єднати з людиною", "Переводити одразу", "Лише якщо наполягає (просить двічі)", "Ніколи не переводити — Набіл впорається сам і приймає повідомлення", "Набіл застосовує це до кожного дзвінка. За «Лише якщо наполягає» та «Ніколи» він натомість промовляє фразу нижче й продовжує допомагати. Якщо збій стався в самого ШІ, дзвінок усе одно надійде на ваш телефон, щоб ніхто не лишився без відповіді.", "Що Набіл каже замість переведення", "Промовляється слово в слово. Залиште порожнім, щоб використати: «Наші працівники зараз зайняті приготуванням замовлень і не можуть відповісти на дзвінок, але я можу допомогти з усім, що стосується ресторану.»", "Пропонувати прийняти повідомлення", "Якщо дзвінок не можна перевести, Набіл пропонує прийняти повідомлення і надсилає його SMS на ваш номер для переведення (або телефон для сповіщень).", "Повідомлення прийнято"],
  ca: ["Quan qui truca demana parlar amb una persona", "Transferir de seguida", "Només si insisteix (ho demana dues vegades)", "No transferir mai — el Nabil se n'encarrega i pren missatges", "El Nabil ho aplica a cada trucada. Amb «Només si insisteix» i «Mai», diu la frase de sota en comptes de transferir i continua ajudant. Si la mateixa IA falla, la trucada continua sonant al vostre telèfon perquè ningú es quedi sense resposta.", "Què diu el Nabil en comptes de transferir", "Es diu paraula per paraula. Deixeu-ho buit per a: «El nostre personal està ocupat preparant comandes i ara mateix no pot atendre trucades, però puc ajudar-lo amb qualsevol cosa sobre el restaurant.»", "Oferir prendre un missatge", "Quan no es pot passar la trucada, el Nabil ofereix prendre un missatge i l'envia per SMS al vostre número de transferència (o al telèfon d'alertes).", "Missatge pres"],
  id: ["Saat penelepon meminta bicara dengan orang", "Alihkan segera", "Hanya jika memaksa (meminta dua kali)", "Jangan pernah alihkan — Nabil menangani dan mencatat pesan", "Nabil menerapkan ini pada setiap panggilan. Dengan “Hanya jika memaksa” dan “Jangan pernah”, Nabil mengucapkan kalimat di bawah ini sebagai gantinya dan terus membantu. Jika AI-nya sendiri bermasalah, panggilan tetap berdering di telepon Anda agar tidak ada yang dibiarkan menunggu.", "Apa yang Nabil katakan alih-alih mengalihkan", "Diucapkan kata demi kata. Kosongkan untuk: “Staf kami sedang sibuk menyiapkan pesanan dan tidak bisa menerima telepon saat ini, tetapi saya bisa membantu untuk apa pun tentang restoran.”", "Tawarkan untuk mencatat pesan", "Saat penelepon tidak bisa dialihkan, Nabil menawarkan untuk mencatat pesan dan mengirimkannya lewat SMS ke nomor pengalihan Anda (atau telepon peringatan).", "Pesan dicatat"],
  vi: ["Khi người gọi yêu cầu nói chuyện với người thật", "Chuyển máy ngay", "Chỉ khi họ nài nỉ (hỏi hai lần)", "Không bao giờ chuyển máy — Nabil tự xử lý và ghi lại lời nhắn", "Nabil áp dụng điều này cho mọi cuộc gọi. Với “Chỉ khi họ nài nỉ” và “Không bao giờ”, Nabil sẽ nói câu bên dưới thay vì chuyển máy và tiếp tục hỗ trợ. Nếu chính AI gặp sự cố, cuộc gọi vẫn đổ chuông trên điện thoại của bạn để không ai bị bỏ lỡ.", "Nabil nói gì thay vì chuyển máy", "Được nói nguyên văn. Để trống để dùng: “Nhân viên của chúng tôi đang bận chuẩn bị đơn hàng và hiện không thể nhận cuộc gọi, nhưng tôi có thể giúp mọi việc liên quan đến nhà hàng.”", "Đề nghị ghi lại lời nhắn", "Khi không thể chuyển máy, Nabil đề nghị ghi lại lời nhắn và nhắn tin đến số chuyển máy của bạn (hoặc điện thoại cảnh báo).", "Đã ghi lời nhắn"],
  th: ["เมื่อผู้โทรขอคุยกับพนักงาน", "โอนสายทันที", "เฉพาะเมื่อยืนยัน (ขอสองครั้ง)", "ไม่โอนสายเลย — Nabil จัดการเองและรับฝากข้อความ", "Nabil ใช้กฎนี้กับทุกสาย เมื่อเลือก “เฉพาะเมื่อยืนยัน” และ “ไม่โอนสายเลย” Nabil จะพูดประโยคด้านล่างแทนและช่วยเหลือต่อ หากตัว AI เองขัดข้อง สายจะยังดังที่โทรศัพท์ของคุณเพื่อไม่ให้ใครถูกทิ้งไว้", "สิ่งที่ Nabil พูดแทนการโอนสาย", "พูดตามคำต่อคำ เว้นว่างเพื่อใช้: “ตอนนี้พนักงานของเรากำลังเตรียมออเดอร์อยู่จึงรับสายไม่ได้ แต่ฉันช่วยเรื่องเกี่ยวกับร้านได้ทุกอย่างค่ะ”", "เสนอรับฝากข้อความ", "เมื่อโอนสายไม่ได้ Nabil จะเสนอรับฝากข้อความและส่ง SMS ไปยังหมายเลขโอนสายของคุณ (หรือโทรศัพท์แจ้งเตือน)", "รับฝากข้อความแล้ว"],
  zh: ["当来电者要求找人工时", "立即转接", "仅在坚持时转接（询问两次）", "从不转接——由 Nabil 处理并留言", "Nabil 会在每次通话中执行此设置。选择“仅在坚持时”和“从不”时，Nabil 会改为说出下面的话并继续提供帮助。如果 AI 本身出现故障，来电仍会转到您的电话，确保没有人被晾着。", "Nabil 不转接时说的话", "逐字说出。留空则使用：“我们的员工正忙着准备订单，现在无法接听电话，但关于餐厅的任何事情我都可以帮您。”", "主动提出留言", "无法转接时，Nabil 会主动提出留言，并通过短信发送到您的转接号码（或提醒电话）。", "已留言"],
  ja: ["お客様が担当者を希望したとき", "すぐに転送する", "強く希望した場合のみ（2回求めたとき）", "転送しない — Nabil が対応し、伝言を預かる", "Nabil はすべての通話でこの設定を適用します。「強く希望した場合のみ」と「転送しない」では、代わりに下の文を伝えて対応を続けます。AI 自体に障害が起きた場合は、誰も取り残されないよう、通話はこれまでどおりお店の電話に着信します。", "転送の代わりに Nabil が伝える内容", "そのまま一字一句読み上げます。空欄の場合：「スタッフはただいま注文の準備で手が離せず、お電話に出ることができませんが、お店に関することでしたら私が対応いたします。」", "伝言を預かることを提案する", "転送できないとき、Nabil は伝言を預かることを提案し、転送先番号（または通知用電話）に SMS で送ります。", "伝言あり"],
  ko: ["전화한 고객이 직원 연결을 요청할 때", "바로 연결", "고객이 고집할 때만 (두 번 요청)", "연결하지 않음 — Nabil이 처리하고 메시지를 받음", "Nabil은 모든 통화에 이 설정을 적용합니다. “고객이 고집할 때만”과 “연결하지 않음”에서는 대신 아래 문장을 말하고 계속 도와드립니다. AI 자체에 문제가 생기면 아무도 방치되지 않도록 통화는 여전히 매장 전화로 울립니다.", "연결 대신 Nabil이 하는 말", "그대로 읽습니다. 비워 두면 다음 문장을 사용합니다: “직원들이 지금 주문 준비로 바빠서 전화를 받을 수 없지만, 매장에 관한 일은 제가 도와드릴 수 있어요.”", "메시지 남기기 제안", "연결할 수 없을 때 Nabil이 메시지를 받아 연결 번호(또는 알림 전화)로 문자로 보냅니다.", "메시지 접수"],
  ar: ["عندما يطلب المتصل التحدث مع شخص", "التحويل فورًا", "فقط إذا أصرّ (طلب مرتين)", "عدم التحويل أبدًا — يتولى نبيل الأمر ويأخذ الرسائل", "يطبّق نبيل هذا على كل مكالمة. مع «فقط إذا أصرّ» و«أبدًا»، يقول الجملة أدناه بدلًا من ذلك ويواصل المساعدة. إذا تعطّل الذكاء الاصطناعي نفسه، فستظل المكالمة ترنّ على هاتفك حتى لا يبقى أحد دون رد.", "ما يقوله نبيل بدلًا من التحويل", "يُقال حرفيًا. اتركه فارغًا لاستخدام: «موظفونا مشغولون حاليًا بتحضير الطلبات ولا يمكنهم الرد على المكالمات الآن، لكن يمكنني مساعدتك في أي شيء يخص المطعم.»", "عرض أخذ رسالة", "عندما يتعذّر تحويل المتصل، يعرض نبيل أخذ رسالة ويرسلها برسالة نصية إلى رقم التحويل (أو هاتف التنبيهات).", "تم أخذ رسالة"],
  he: ["כשהמתקשר מבקש לדבר עם אדם", "להעביר מיד", "רק אם מתעקשים (מבקשים פעמיים)", "לא להעביר לעולם — נביל מטפל ולוקח הודעות", "נביל אוכף זאת בכל שיחה. עם ״רק אם מתעקשים״ ו״לעולם לא״, הוא אומר במקום זאת את המשפט שלמטה וממשיך לעזור. אם הבינה המלאכותית עצמה נתקעת, השיחה עדיין מצלצלת בטלפון שלך כדי שאף אחד לא יישאר ללא מענה.", "מה נביל אומר במקום להעביר", "נאמר מילה במילה. השאירו ריק עבור: ״הצוות שלנו עסוק כרגע בהכנת הזמנות ולא יכול לענות לשיחות, אבל אני יכול לעזור בכל דבר שקשור למסעדה.״", "להציע לקחת הודעה", "כשלא ניתן להעביר את המתקשר, נביל מציע לקחת הודעה ושולח אותה ב-SMS למספר ההעברה שלך (או לטלפון ההתראות).", "נלקחה הודעה"],
  hi: ["जब कॉल करने वाला किसी व्यक्ति से बात करना चाहे", "तुरंत ट्रांसफ़र करें", "सिर्फ़ ज़ोर देने पर (दो बार माँगने पर)", "कभी ट्रांसफ़र न करें — नबील खुद संभालेगा और संदेश लेगा", "नबील इसे हर कॉल पर लागू करता है। “सिर्फ़ ज़ोर देने पर” और “कभी नहीं” में वह इसके बजाय नीचे दी गई बात कहता है और मदद करता रहता है। अगर AI खुद काम करना बंद कर दे, तो कॉल फिर भी आपके फ़ोन पर बजेगी ताकि कोई बिना जवाब के न रहे।", "ट्रांसफ़र करने के बजाय नबील क्या कहेगा", "शब्दशः बोला जाता है। इसके लिए खाली छोड़ें: “हमारा स्टाफ़ अभी ऑर्डर तैयार करने में व्यस्त है और कॉल नहीं ले सकता, लेकिन रेस्तरां से जुड़ी किसी भी बात में मैं आपकी मदद कर सकता हूँ।”", "संदेश लेने की पेशकश करें", "जब कॉल ट्रांसफ़र नहीं हो सकती, तो नबील संदेश लेने की पेशकश करता है और उसे आपके ट्रांसफ़र नंबर (या अलर्ट फ़ोन) पर SMS कर देता है।", "संदेश लिया गया"],
};

function main() {
  const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".json"));
  let changed = 0;
  for (const f of files) {
    const locale = f.replace(/\.json$/, "");
    const t = T[locale];
    if (!t || t.length !== CONFIG_KEYS.length + 1) {
      console.error(`✗ no translation block for ${locale} (${f})`);
      process.exit(1);
    }
    const file = path.join(DIR, f);
    const json = JSON.parse(fs.readFileSync(file, "utf8"));
    const page = json?.admin?.phoneOrderingPage;
    if (!page?.config || !page?.callLog?.outcome) {
      console.error(`✗ ${locale}: admin.phoneOrderingPage.config / callLog.outcome missing`);
      process.exit(1);
    }
    let touched = false;
    CONFIG_KEYS.forEach((k, i) => {
      if (page.config[k] !== t[i]) { page.config[k] = t[i]; touched = true; }
    });
    if (page.callLog.outcome.message_taken !== t[CONFIG_KEYS.length]) {
      page.callLog.outcome.message_taken = t[CONFIG_KEYS.length];
      touched = true;
    }
    if (touched) {
      fs.writeFileSync(file, JSON.stringify(json, null, 2) + "\n");
      changed++;
    }
  }
  console.log(`✓ ${files.length} locale files checked, ${changed} updated`);
}

main();
