/**
 * admin.promoStepConfig.pctBasis* — percentage-promo wording for the discount
 * basis selector (Luigi 2026-08-09).
 *
 * The control is shared with free-item deals, where it is worded "Charges on
 * the FREE item". On a percentage promo there is no free item, so that wording
 * told an owner nothing about what he was actually choosing — and choosing
 * "…& Sizes" makes the percentage apply to the CHEAPEST size, so a 20%-off
 * promo paid 20% of a $17 small wing pack even on a $45 large one. Same engine
 * behaviour, honest labels, plus a warning on the size option.
 *
 *   npx tsx scripts/i18n-add-pct-basis-keys.ts
 *
 * Idempotent — never overwrites an existing value.
 */
import fs from "node:fs";
import path from "node:path";
import { SUPPORTED_LOCALES } from "../src/lib/locales";

type B = { label: string; whole: string; addons: string; addonsSizes: string; hint: string; warn: string };

const T: Record<string, B> = {
  en: { label: "What the discount applies to", whole: "The whole item — add-ons and size upgrade included (recommended)", addons: "Base price only — add-ons and choices are not discounted", addonsSizes: "Smallest size's base price only — size upgrade and add-ons are not discounted", hint: "Most \"X% off\" promotions should use the first option.", warn: "Heads up: with this option the discount does NOT grow when a customer picks a larger size — a 20% promo gives the same amount on the smallest and the largest size." },
  it: { label: "A cosa si applica lo sconto", whole: "L'intero articolo — aggiunte e formato inclusi (consigliato)", addons: "Solo il prezzo base — aggiunte e scelte non scontate", addonsSizes: "Solo il prezzo base del formato più piccolo — formato e aggiunte non scontati", hint: "La maggior parte delle promozioni \"X% di sconto\" dovrebbe usare la prima opzione.", warn: "Attenzione: con questa opzione lo sconto NON aumenta se il cliente sceglie un formato più grande — una promo del 20% dà lo stesso importo sul formato più piccolo e su quello più grande." },
  fr: { label: "Ce à quoi la remise s'applique", whole: "L'article entier — suppléments et taille inclus (recommandé)", addons: "Prix de base uniquement — suppléments et choix non remisés", addonsSizes: "Prix de base de la plus petite taille — taille et suppléments non remisés", hint: "La plupart des promotions « X % de remise » devraient utiliser la première option.", warn: "Attention : avec cette option, la remise n'augmente PAS si le client choisit une taille plus grande — une promo de 20 % donne le même montant sur la plus petite et la plus grande taille." },
  es: { label: "A qué se aplica el descuento", whole: "El artículo completo — extras y tamaño incluidos (recomendado)", addons: "Solo el precio base — extras y opciones sin descuento", addonsSizes: "Solo el precio base del tamaño más pequeño — tamaño y extras sin descuento", hint: "La mayoría de las promociones de \"X % de descuento\" deberían usar la primera opción.", warn: "Aviso: con esta opción el descuento NO aumenta si el cliente elige un tamaño mayor — una promo del 20 % da el mismo importe en el tamaño más pequeño y en el más grande." },
  de: { label: "Worauf der Rabatt angewendet wird", whole: "Der ganze Artikel — Extras und Größen-Upgrade inklusive (empfohlen)", addons: "Nur der Grundpreis — Extras und Auswahlen werden nicht rabattiert", addonsSizes: "Nur der Grundpreis der kleinsten Größe — Größen-Upgrade und Extras ohne Rabatt", hint: "Die meisten \"X % Rabatt\"-Aktionen sollten die erste Option verwenden.", warn: "Achtung: Mit dieser Option wächst der Rabatt NICHT, wenn der Kunde eine größere Größe wählt — eine 20 %-Aktion ergibt bei der kleinsten und der größten Größe denselben Betrag." },
  pt: { label: "A que se aplica o desconto", whole: "O artigo completo — extras e tamanho incluídos (recomendado)", addons: "Apenas o preço base — extras e escolhas não têm desconto", addonsSizes: "Apenas o preço base do tamanho mais pequeno — tamanho e extras sem desconto", hint: "A maioria das promoções \"X% de desconto\" deve usar a primeira opção.", warn: "Atenção: com esta opção o desconto NÃO aumenta se o cliente escolher um tamanho maior — uma promoção de 20% dá o mesmo valor no tamanho mais pequeno e no maior." },
  "pt-BR": { label: "A que o desconto se aplica", whole: "O item inteiro — adicionais e tamanho incluídos (recomendado)", addons: "Apenas o preço base — adicionais e escolhas sem desconto", addonsSizes: "Apenas o preço base do menor tamanho — tamanho e adicionais sem desconto", hint: "A maioria das promoções \"X% de desconto\" deve usar a primeira opção.", warn: "Atenção: com esta opção o desconto NÃO aumenta se o cliente escolher um tamanho maior — uma promoção de 20% dá o mesmo valor no menor e no maior tamanho." },
  nl: { label: "Waarop de korting van toepassing is", whole: "Het hele item — extra's en maatupgrade inbegrepen (aanbevolen)", addons: "Alleen de basisprijs — extra's en keuzes krijgen geen korting", addonsSizes: "Alleen de basisprijs van de kleinste maat — maatupgrade en extra's zonder korting", hint: "De meeste \"X% korting\"-acties zouden de eerste optie moeten gebruiken.", warn: "Let op: met deze optie groeit de korting NIET als de klant een grotere maat kiest — een actie van 20% geeft hetzelfde bedrag bij de kleinste en de grootste maat." },
  pl: { label: "Do czego stosuje się rabat", whole: "Cała pozycja — dodatki i większy rozmiar wliczone (zalecane)", addons: "Tylko cena bazowa — dodatki i opcje bez rabatu", addonsSizes: "Tylko cena bazowa najmniejszego rozmiaru — rozmiar i dodatki bez rabatu", hint: "Większość promocji \"X% zniżki\" powinna używać pierwszej opcji.", warn: "Uwaga: przy tej opcji rabat NIE rośnie, gdy klient wybierze większy rozmiar — promocja 20% daje tę samą kwotę przy najmniejszym i największym rozmiarze." },
  ro: { label: "La ce se aplică reducerea", whole: "Întregul produs — extra și mărimea incluse (recomandat)", addons: "Doar prețul de bază — extrele și opțiunile nu se reduc", addonsSizes: "Doar prețul de bază al celei mai mici mărimi — mărimea și extrele fără reducere", hint: "Majoritatea promoțiilor \"X% reducere\" ar trebui să folosească prima opțiune.", warn: "Atenție: cu această opțiune reducerea NU crește dacă clientul alege o mărime mai mare — o promoție de 20% dă aceeași sumă la cea mai mică și la cea mai mare mărime." },
  hu: { label: "Mire vonatkozik a kedvezmény", whole: "A teljes tétel — feltétek és méretfelár is (ajánlott)", addons: "Csak az alapár — a feltétekre és választásokra nincs kedvezmény", addonsSizes: "Csak a legkisebb méret alapára — méret és feltétek kedvezmény nélkül", hint: "A legtöbb \"X% kedvezmény\" akcióhoz az első lehetőséget érdemes választani.", warn: "Figyelem: ezzel a beállítással a kedvezmény NEM nő, ha a vendég nagyobb méretet választ — egy 20%-os akció ugyanannyit ad a legkisebb és a legnagyobb méretnél." },
  cs: { label: "Na co se sleva vztahuje", whole: "Celá položka — přílohy i větší velikost (doporučeno)", addons: "Pouze základní cena — přílohy a volby bez slevy", addonsSizes: "Pouze základní cena nejmenší velikosti — velikost a přílohy bez slevy", hint: "Většina akcí \"X % sleva\" by měla používat první možnost.", warn: "Pozor: u této možnosti sleva NEROSTE, když si zákazník vybere větší velikost — akce 20 % dá stejnou částku u nejmenší i největší velikosti." },
  sk: { label: "Na čo sa zľava vzťahuje", whole: "Celá položka — prílohy aj väčšia veľkosť (odporúčané)", addons: "Iba základná cena — prílohy a voľby bez zľavy", addonsSizes: "Iba základná cena najmenšej veľkosti — veľkosť a prílohy bez zľavy", hint: "Väčšina akcií \"X % zľava\" by mala používať prvú možnosť.", warn: "Pozor: pri tejto možnosti zľava NERASTIE, keď si zákazník vyberie väčšiu veľkosť — akcia 20 % dá rovnakú sumu pri najmenšej aj najväčšej veľkosti." },
  sl: { label: "Na kaj se popust nanaša", whole: "Celoten izdelek — dodatki in večja velikost vključeni (priporočeno)", addons: "Samo osnovna cena — dodatki in izbire brez popusta", addonsSizes: "Samo osnovna cena najmanjše velikosti — velikost in dodatki brez popusta", hint: "Večina akcij \"X % popusta\" naj uporabi prvo možnost.", warn: "Pozor: pri tej možnosti popust NE raste, če stranka izbere večjo velikost — 20-odstotna akcija da enak znesek pri najmanjši in največji velikosti." },
  hr: { label: "Na što se popust primjenjuje", whole: "Cijela stavka — dodaci i veća veličina uključeni (preporučeno)", addons: "Samo osnovna cijena — dodaci i izbori bez popusta", addonsSizes: "Samo osnovna cijena najmanje veličine — veličina i dodaci bez popusta", hint: "Većina akcija \"X% popusta\" trebala bi koristiti prvu opciju.", warn: "Pažnja: uz ovu opciju popust NE raste ako kupac odabere veću veličinu — akcija od 20% daje isti iznos na najmanjoj i najvećoj veličini." },
  sr: { label: "Na šta se popust primenjuje", whole: "Cela stavka — dodaci i veća veličina uključeni (preporučeno)", addons: "Samo osnovna cena — dodaci i izbori bez popusta", addonsSizes: "Samo osnovna cena najmanje veličine — veličina i dodaci bez popusta", hint: "Većina akcija \"X% popusta\" treba da koristi prvu opciju.", warn: "Pažnja: uz ovu opciju popust NE raste ako kupac izabere veću veličinu — akcija od 20% daje isti iznos na najmanjoj i najvećoj veličini." },
  bg: { label: "За какво важи отстъпката", whole: "Целият артикул — добавки и по-голям размер включени (препоръчано)", addons: "Само базовата цена — добавките и изборите не се отстъпват", addonsSizes: "Само базовата цена на най-малкия размер — размерът и добавките без отстъпка", hint: "Повечето промоции \"X% отстъпка\" трябва да използват първата опция.", warn: "Внимание: с тази опция отстъпката НЕ расте, когато клиентът избере по-голям размер — промоция от 20% дава същата сума при най-малкия и най-големия размер." },
  el: { label: "Σε τι εφαρμόζεται η έκπτωση", whole: "Ολόκληρο το είδος — πρόσθετα και μεγαλύτερο μέγεθος (συνιστάται)", addons: "Μόνο η βασική τιμή — τα πρόσθετα δεν εκπίπτουν", addonsSizes: "Μόνο η βασική τιμή του μικρότερου μεγέθους — μέγεθος και πρόσθετα χωρίς έκπτωση", hint: "Οι περισσότερες προσφορές \"X% έκπτωση\" πρέπει να χρησιμοποιούν την πρώτη επιλογή.", warn: "Προσοχή: με αυτήν την επιλογή η έκπτωση ΔΕΝ αυξάνεται όταν ο πελάτης επιλέγει μεγαλύτερο μέγεθος — μια προσφορά 20% δίνει το ίδιο ποσό στο μικρότερο και στο μεγαλύτερο μέγεθος." },
  tr: { label: "İndirimin uygulandığı tutar", whole: "Ürünün tamamı — ekstralar ve boy farkı dahil (önerilen)", addons: "Yalnızca temel fiyat — ekstralara indirim uygulanmaz", addonsSizes: "Yalnızca en küçük boyun temel fiyatı — boy farkı ve ekstralar indirimsiz", hint: "\"%X indirim\" kampanyalarının çoğu ilk seçeneği kullanmalıdır.", warn: "Dikkat: bu seçenekte müşteri daha büyük boy seçtiğinde indirim ARTMAZ — %20'lik bir kampanya en küçük ve en büyük boyda aynı tutarı verir." },
  uk: { label: "На що поширюється знижка", whole: "Уся позиція — додатки та більший розмір включно (рекомендовано)", addons: "Лише базова ціна — додатки без знижки", addonsSizes: "Лише базова ціна найменшого розміру — розмір і додатки без знижки", hint: "Більшість акцій \"знижка X%\" мають використовувати перший варіант.", warn: "Увага: з цим варіантом знижка НЕ зростає, коли клієнт обирає більший розмір — акція 20% дає однакову суму для найменшого й найбільшого розміру." },
  ru: { label: "К чему применяется скидка", whole: "Вся позиция — добавки и больший размер включены (рекомендуется)", addons: "Только базовая цена — добавки без скидки", addonsSizes: "Только базовая цена самого маленького размера — размер и добавки без скидки", hint: "Большинство акций \"скидка X%\" должны использовать первый вариант.", warn: "Внимание: с этим вариантом скидка НЕ растёт, когда клиент выбирает больший размер — акция 20% даёт одинаковую сумму для самого маленького и самого большого размера." },
  sv: { label: "Vad rabatten gäller", whole: "Hela varan — tillbehör och storleksuppgradering ingår (rekommenderas)", addons: "Endast grundpriset — tillbehör och val rabatteras inte", addonsSizes: "Endast minsta storlekens grundpris — storlek och tillbehör utan rabatt", hint: "De flesta \"X % rabatt\"-kampanjer bör använda det första alternativet.", warn: "Obs: med det här alternativet ökar INTE rabatten när kunden väljer en större storlek — en 20 %-kampanj ger samma belopp på minsta och största storleken." },
  nb: { label: "Hva rabatten gjelder", whole: "Hele varen — tillegg og størrelsesoppgradering inkludert (anbefalt)", addons: "Kun grunnprisen — tillegg og valg får ikke rabatt", addonsSizes: "Kun minste størrelses grunnpris — størrelse og tillegg uten rabatt", hint: "De fleste \"X % rabatt\"-kampanjer bør bruke det første alternativet.", warn: "Merk: med dette alternativet øker IKKE rabatten når kunden velger en større størrelse — en 20 %-kampanje gir samme beløp på minste og største størrelse." },
  da: { label: "Hvad rabatten gælder", whole: "Hele varen — tilbehør og størrelsesopgradering inkluderet (anbefales)", addons: "Kun grundprisen — tilbehør og valg får ikke rabat", addonsSizes: "Kun mindste størrelses grundpris — størrelse og tilbehør uden rabat", hint: "De fleste \"X % rabat\"-kampagner bør bruge den første mulighed.", warn: "Bemærk: med denne mulighed vokser rabatten IKKE, når kunden vælger en større størrelse — en 20 %-kampagne giver samme beløb på mindste og største størrelse." },
  fi: { label: "Mihin alennus kohdistuu", whole: "Koko tuote — lisät ja koon korotus mukaan lukien (suositus)", addons: "Vain perushinta — lisiä ei alenneta", addonsSizes: "Vain pienimmän koon perushinta — koko ja lisät ilman alennusta", hint: "Useimpien \"X % alennus\" -kampanjoiden kannattaa käyttää ensimmäistä vaihtoehtoa.", warn: "Huomio: tällä vaihtoehdolla alennus EI kasva, kun asiakas valitsee isomman koon — 20 %:n kampanja antaa saman summan pienimmässä ja suurimmassa koossa." },
  et: { label: "Millele allahindlus kehtib", whole: "Kogu toode — lisandid ja suurem suurus kaasa arvatud (soovitatav)", addons: "Ainult põhihind — lisandeid ei soodustata", addonsSizes: "Ainult väikseima suuruse põhihind — suurus ja lisandid ilma soodustuseta", hint: "Enamik \"X% soodustust\" kampaaniaid peaks kasutama esimest valikut.", warn: "Tähelepanu: selle valikuga EI kasva soodustus, kui klient valib suurema suuruse — 20% kampaania annab sama summa väikseima ja suurima suuruse puhul." },
  lv: { label: "Uz ko attiecas atlaide", whole: "Visa prece — piedevas un lielāks izmērs iekļauts (ieteicams)", addons: "Tikai pamatcena — piedevām atlaide netiek piemērota", addonsSizes: "Tikai mazākā izmēra pamatcena — izmērs un piedevas bez atlaides", hint: "Vairumam \"X% atlaide\" akciju vajadzētu izmantot pirmo iespēju.", warn: "Uzmanību: ar šo iespēju atlaide NEPIEAUG, ja klients izvēlas lielāku izmēru — 20% akcija dod tādu pašu summu mazākajam un lielākajam izmēram." },
  lt: { label: "Kam taikoma nuolaida", whole: "Visai prekei — priedai ir didesnis dydis įskaičiuoti (rekomenduojama)", addons: "Tik bazinė kaina — priedams nuolaida netaikoma", addonsSizes: "Tik mažiausio dydžio bazinė kaina — dydis ir priedai be nuolaidos", hint: "Daugumai \"X% nuolaida\" akcijų reikėtų rinktis pirmą parinktį.", warn: "Dėmesio: su šia parinktimi nuolaida NEDIDĖJA, kai klientas pasirenka didesnį dydį — 20% akcija duoda tą pačią sumą mažiausiam ir didžiausiam dydžiui." },
  ca: { label: "A què s'aplica el descompte", whole: "L'article sencer — extres i mida inclosos (recomanat)", addons: "Només el preu base — extres i opcions sense descompte", addonsSizes: "Només el preu base de la mida més petita — mida i extres sense descompte", hint: "La majoria de promocions \"X% de descompte\" haurien d'usar la primera opció.", warn: "Atenció: amb aquesta opció el descompte NO augmenta si el client tria una mida més gran — una promo del 20% dóna el mateix import a la mida més petita i a la més gran." },
  id: { label: "Diskon berlaku untuk apa", whole: "Seluruh item — tambahan dan ukuran termasuk (disarankan)", addons: "Hanya harga dasar — tambahan tidak didiskon", addonsSizes: "Hanya harga dasar ukuran terkecil — ukuran dan tambahan tanpa diskon", hint: "Sebagian besar promo \"diskon X%\" sebaiknya memakai opsi pertama.", warn: "Perhatian: dengan opsi ini diskon TIDAK bertambah saat pelanggan memilih ukuran lebih besar — promo 20% memberi jumlah yang sama pada ukuran terkecil dan terbesar." },
  vi: { label: "Giảm giá áp dụng cho", whole: "Toàn bộ món — gồm cả topping và nâng cỡ (khuyến nghị)", addons: "Chỉ giá gốc — topping và tuỳ chọn không được giảm", addonsSizes: "Chỉ giá gốc của cỡ nhỏ nhất — cỡ lớn và topping không được giảm", hint: "Hầu hết khuyến mãi \"giảm X%\" nên dùng tuỳ chọn đầu tiên.", warn: "Lưu ý: với tuỳ chọn này, mức giảm KHÔNG tăng khi khách chọn cỡ lớn hơn — khuyến mãi 20% cho cùng một số tiền ở cỡ nhỏ nhất và lớn nhất." },
  th: { label: "ส่วนลดใช้กับอะไร", whole: "ทั้งรายการ — รวมท็อปปิงและการอัปไซซ์ (แนะนำ)", addons: "เฉพาะราคาพื้นฐาน — ท็อปปิงและตัวเลือกไม่ลด", addonsSizes: "เฉพาะราคาพื้นฐานของขนาดเล็กสุด — ขนาดและท็อปปิงไม่ลด", hint: "โปรโมชัน \"ลด X%\" ส่วนใหญ่ควรใช้ตัวเลือกแรก", warn: "โปรดทราบ: ตัวเลือกนี้ส่วนลดจะไม่เพิ่มขึ้นเมื่อลูกค้าเลือกขนาดใหญ่ขึ้น — โปร 20% จะให้จำนวนเงินเท่ากันทั้งขนาดเล็กสุดและใหญ่สุด" },
  zh: { label: "折扣适用范围", whole: "整份商品 — 含加料与加大尺寸（推荐）", addons: "仅基础价格 — 加料与选项不打折", addonsSizes: "仅最小尺寸的基础价格 — 加大尺寸与加料不打折", hint: "大多数“X% 折扣”促销应选择第一项。", warn: "注意：使用此选项时，顾客选择更大尺寸折扣不会增加 — 20% 的促销在最小和最大尺寸上给出相同的金额。" },
  ja: { label: "割引の適用対象", whole: "商品全体 — トッピングとサイズ変更を含む（推奨）", addons: "基本価格のみ — トッピングや選択は割引対象外", addonsSizes: "最小サイズの基本価格のみ — サイズ変更とトッピングは割引対象外", hint: "「X%オフ」の多くは最初の選択肢が適切です。", warn: "ご注意：この設定では、お客様が大きいサイズを選んでも割引額は増えません。20%オフでも最小サイズと最大サイズで同じ金額になります。" },
  ko: { label: "할인 적용 대상", whole: "상품 전체 — 추가 항목과 사이즈 업그레이드 포함 (권장)", addons: "기본 가격만 — 추가 항목은 할인되지 않음", addonsSizes: "가장 작은 사이즈의 기본 가격만 — 사이즈와 추가 항목은 할인 제외", hint: "대부분의 \"X% 할인\" 프로모션은 첫 번째 옵션을 사용해야 합니다.", warn: "주의: 이 옵션에서는 고객이 더 큰 사이즈를 선택해도 할인액이 늘지 않습니다 — 20% 할인이 최소 사이즈와 최대 사이즈에서 같은 금액이 됩니다." },
  ar: { label: "ما ينطبق عليه الخصم", whole: "الصنف بالكامل — بما في ذلك الإضافات وترقية الحجم (موصى به)", addons: "السعر الأساسي فقط — لا خصم على الإضافات", addonsSizes: "السعر الأساسي لأصغر حجم فقط — الحجم والإضافات بدون خصم", hint: "معظم عروض \"خصم X%\" ينبغي أن تستخدم الخيار الأول.", warn: "تنبيه: مع هذا الخيار لا يزيد الخصم عندما يختار العميل حجمًا أكبر — عرض 20% يعطي المبلغ نفسه لأصغر وأكبر حجم." },
  he: { label: "על מה חל ההנחה", whole: "הפריט כולו — כולל תוספות ושדרוג גודל (מומלץ)", addons: "מחיר הבסיס בלבד — אין הנחה על תוספות", addonsSizes: "מחיר הבסיס של הגודל הקטן ביותר בלבד — גודל ותוספות ללא הנחה", hint: "רוב מבצעי \"X% הנחה\" צריכים להשתמש באפשרות הראשונה.", warn: "לתשומת לבך: באפשרות זו ההנחה אינה גדלה כשלקוח בוחר גודל גדול יותר — מבצע של 20% ייתן את אותו סכום בגודל הקטן ובגדול." },
  hi: { label: "छूट किस पर लागू होगी", whole: "पूरा आइटम — ऐड-ऑन और बड़ा साइज़ शामिल (अनुशंसित)", addons: "केवल आधार मूल्य — ऐड-ऑन पर छूट नहीं", addonsSizes: "केवल सबसे छोटे साइज़ का आधार मूल्य — साइज़ और ऐड-ऑन पर छूट नहीं", hint: "अधिकांश \"X% छूट\" प्रोमो में पहला विकल्प चुनें।", warn: "ध्यान दें: इस विकल्प में ग्राहक द्वारा बड़ा साइज़ चुनने पर छूट नहीं बढ़ती — 20% का प्रोमो सबसे छोटे और सबसे बड़े साइज़ पर समान राशि देगा।" },
};

const KEYS: (keyof B)[] = ["label", "whole", "addons", "addonsSizes", "hint", "warn"];
const NAME: Record<keyof B, string> = {
  label: "pctBasisLabel", whole: "pctBasisWhole", addons: "pctBasisAddons",
  addonsSizes: "pctBasisAddonsSizes", hint: "pctBasisHint", warn: "pctBasisSizeWarning",
};

const DIR = path.join(process.cwd(), "src", "messages");
let touched = 0;
const gaps: string[] = [];

for (const locale of SUPPORTED_LOCALES) {
  const file = path.join(DIR, `${locale}.json`);
  const json = JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, any>;
  const b = T[locale];
  if (!b) { gaps.push(locale); continue; }
  json.admin = json.admin ?? {};
  json.admin.promoStepConfig = json.admin.promoStepConfig ?? {};
  let n = 0;
  for (const k of KEYS) {
    if (typeof json.admin.promoStepConfig[NAME[k]] !== "string") { json.admin.promoStepConfig[NAME[k]] = b[k]; n++; }
  }
  if (n > 0) { fs.writeFileSync(file, JSON.stringify(json, null, 2) + "\n", "utf8"); touched++; }
  console.log(`  ${locale.padEnd(6)} +${n}`);
}

if (gaps.length) console.error(`\n⚠️  missing bundle for: ${gaps.join(", ")}`);
console.log(`\n✅ ${touched}/${SUPPORTED_LOCALES.length} locale files updated.`);
